import type { ExercisesDocType } from "./exercises";

export const dumbbellExercises: ExercisesDocType[] = [
  {
    id: "dumbbell-row-one-arm",
    name: "Dumbbell Row (One Arm)",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-squat",
    name: "Dumbbell Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-goblet-squat",
    name: "Dumbbell Goblet Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-lunge",
    name: "Dumbbell Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-reverse-lunge",
    name: "Dumbbell Reverse Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-walking-lunge",
    name: "Dumbbell Walking Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-bulgarian-split-squat",
    name: "Dumbbell Bulgarian Split Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-split-squat",
    name: "Dumbbell Split Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-step-up",
    name: "Dumbbell Step Up",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-deadlift",
    name: "Dumbbell Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-stiff-leg-deadlift",
    name: "Dumbbell Stiff Leg Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-incline-bench-press",
    name: "Dumbbell Incline Bench Press",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "inclinebench"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-decline-bench-press",
    name: "Dumbbell Decline Bench Press",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-chest-fly",
    name: "Dumbbell Chest Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-incline-fly",
    name: "Dumbbell Incline Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "inclinebench"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-pullover",
    name: "Dumbbell Pullover",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["compound"],
  },
  {
    id: "dumbbell-overhead-press",
    name: "Dumbbell Overhead Press",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-arnold-press",
    name: "Dumbbell Arnold Press",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-front-raise",
    name: "Dumbbell Front Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-rear-delt-fly",
    name: "Dumbbell Rear Delt Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-upright-row",
    name: "Dumbbell Upright Row",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },
  {
    id: "dumbbell-shrug",
    name: "Dumbbell Shrug",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-bent-over-row",
    name: "Dumbbell Bent Over Row",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-single-arm-row",
    name: "Dumbbell Single Arm Row",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-renegade-row",
    name: "Dumbbell Renegade Row",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-bicep-curl",
    name: "Dumbbell Bicep Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-lying-bicep-curl",
    name: "Dumbbell Lying Bicep Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-hammer-curl",
    name: "Dumbbell Hammer Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-concentration-curl",
    name: "Dumbbell Concentration Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-preacher-curl",
    name: "Dumbbell Preacher Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-tricep-extension",
    name: "Dumbbell Tricep Extension",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-overhead-tricep-extension",
    name: "Dumbbell Overhead Tricep Extension",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-tricep-kickback",
    name: "Dumbbell Tricep Kickback",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-chest-press",
    name: "Dumbbell Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-thrusters",
    name: "Dumbbell Thrusters",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-man-makers",
    name: "Dumbbell Man Makers",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-turkish-getup",
    name: "Dumbbell Turkish Get-up",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-farmer-walk",
    name: "Dumbbell Farmer Walk",
    type: "strength",
    track: ["weight", "time"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "dumbbell-calf-raise",
    name: "Dumbbell Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
  {
    id: "dumbbell-wrist-curl",
    name: "Dumbbell Wrist Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["isolation"],
  },
];
