import { type ExercisesDocType } from "./exercises";

export const isometricExercises: ExercisesDocType[] = [
  // Core Isometrics
  {
    id: "plank-hold",
    name: "Plank Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "side-plank-hold",
    name: "Side Plank Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation", "primary"],
  },
  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "dead-bug-hold",
    name: "Dead Bug Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "boat-pose-hold",
    name: "Boat Pose Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },

  // Lower Body Isometrics
  {
    id: "wall-sit",
    name: "Wall Sit",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "single-leg-wall-sit",
    name: "Single Leg Wall Sit",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "squat-hold",
    name: "Squat Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "single-leg-squat-hold",
    name: "Single Leg Squat Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "lunge-hold",
    name: "Lunge Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "reverse-lunge-hold",
    name: "Reverse Lunge Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "lateral-lunge-hold",
    name: "Lateral Lunge Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "calf-raise-hold",
    name: "Calf Raise Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "single-leg-calf-raise-hold",
    name: "Single Leg Calf Raise Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },

  // Upper Body Isometrics
  {
    id: "push-up-hold",
    name: "Push Up Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "push-up-bottom-hold",
    name: "Push Up Bottom Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "pike-push-up-hold",
    name: "Pike Push Up Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "dead-hang",
    name: "Dead Hang",
    type: "strength",
    track: ["time"],
    equipment: ["pullupbar"],
    tags: ["compound", "primary"],
  },
  {
    id: "chin-up-hold",
    name: "Chin Up Hold",
    type: "strength",
    track: ["time"],
    equipment: ["pullupbar"],
    tags: ["compound"],
  },
  {
    id: "pull-up-hold",
    name: "Pull Up Hold",
    type: "strength",
    track: ["time"],
    equipment: ["pullupbar"],
    tags: ["compound"],
  },
  {
    id: "l-sit-hold",
    name: "L-Sit Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Glute Isometrics
  {
    id: "glute-bridge-hold",
    name: "Glute Bridge Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation", "primary"],
  },
  {
    id: "single-leg-glute-bridge-hold",
    name: "Single Leg Glute Bridge Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "hip-thrust-hold",
    name: "Hip Thrust Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "single-leg-hip-thrust-hold",
    name: "Single Leg Hip Thrust Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "clamshell-hold",
    name: "Clamshell Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },

  // Advanced Isometrics
  {
    id: "human-flag-hold",
    name: "Human Flag Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "front-lever-hold",
    name: "Front Lever Hold",
    type: "strength",
    track: ["time"],
    equipment: ["pullupbar"],
    tags: ["compound"],
  },
  {
    id: "back-lever-hold",
    name: "Back Lever Hold",
    type: "strength",
    track: ["time"],
    equipment: ["pullupbar"],
    tags: ["compound"],
  },
  {
    id: "handstand-hold",
    name: "Handstand Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "wall-handstand-hold",
    name: "Wall Handstand Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "pistol-squat-hold",
    name: "Pistol Squat Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Equipment-Based Isometrics
  {
    id: "barbell-squat-hold",
    name: "Barbell Squat Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["barbell"],
    tags: ["compound"],
  },
  {
    id: "barbell-deadlift-hold",
    name: "Barbell Deadlift Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["barbell"],
    tags: ["compound"],
  },
  {
    id: "barbell-overhead-hold",
    name: "Barbell Overhead Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["barbell"],
    tags: ["compound"],
  },
  {
    id: "dumbbell-overhead-hold",
    name: "Dumbbell Overhead Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-overhead-hold",
    name: "Kettlebell Overhead Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "farmers-walk-hold",
    name: "Farmers Walk Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },

  // Specialized Holds
  {
    id: "bear-crawl-hold",
    name: "Bear Crawl Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "crab-walk-hold",
    name: "Crab Walk Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "mountain-climber-hold",
    name: "Mountain Climber Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "reverse-plank-hold",
    name: "Reverse Plank Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "superman-hold",
    name: "Superman Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "bird-dog-hold",
    name: "Bird Dog Hold",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Band/Resistance Isometrics
  {
    id: "band-chest-press-hold",
    name: "Band Chest Press Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-squat-hold",
    name: "Band Squat Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-row-hold",
    name: "Band Row Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-overhead-press-hold",
    name: "Band Overhead Press Hold",
    type: "strength",
    track: ["time", "weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
];
