import { type ExercisesDocType } from "./exercises";

export const plyometricExercises: ExercisesDocType[] = [
  // Jump Fundamentals
  {
    id: "box-jump",
    name: "Box Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "jump-squat",
    name: "Jump Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "broad-jump",
    name: "Broad Jump",
    type: "strength",
    track: ["distance"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "vertical-jump",
    name: "Vertical Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Upper Body Plyometrics
  {
    id: "clap-push-up",
    name: "Clap Push Up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "explosive-push-up",
    name: "Explosive Push Up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  {
    id: "plyo-push-up",
    name: "Plyometric Push Up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Lower Body Jumps
  {
    id: "single-leg-hop",
    name: "Single Leg Hop",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "lateral-bound",
    name: "Lateral Bound",
    type: "strength",
    track: ["distance"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "forward-bound",
    name: "Forward Bound",
    type: "strength",
    track: ["distance"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "depth-jump",
    name: "Depth Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "split-jump",
    name: "Split Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "alternating-jump-lunge",
    name: "Alternating Jump Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "single-leg-box-jump",
    name: "Single Leg Box Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "lateral-box-jump",
    name: "Lateral Box Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Multi-Directional
  {
    id: "star-jump",
    name: "Star Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "tuck-jump",
    name: "Tuck Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "pike-jump",
    name: "Pike Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "180-jump",
    name: "180 Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "360-jump",
    name: "360 Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Reactive/Speed
  {
    id: "pogo-jump",
    name: "Pogo Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "ankle-bounce",
    name: "Ankle Bounce",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "double-leg-bound",
    name: "Double Leg Bound",
    type: "strength",
    track: ["distance"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "triple-jump",
    name: "Triple Jump",
    type: "strength",
    track: ["distance"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Complex Movements
  {
    id: "burpee-box-jump",
    name: "Burpee Box Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "squat-jump-180",
    name: "Squat Jump 180",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "lunge-jump-switch",
    name: "Lunge Jump Switch",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "burpee-broad-jump",
    name: "Burpee Broad Jump",
    type: "strength",
    track: ["distance"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Wall/Equipment Based
  {
    id: "wall-ball-slam",
    name: "Wall Ball Slam",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "slam-ball-overhead",
    name: "Slam Ball Overhead",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "box-jump-over",
    name: "Box Jump Over",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "lateral-box-step-over",
    name: "Lateral Box Step Over",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Cardio Plyometrics
  {
    id: "plyo-jacks",
    name: "Plyometric Jumping Jacks",
    type: "cardio",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "mountain-climber-explosive",
    name: "Explosive Mountain Climber",
    type: "cardio",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "high-knees-explosive",
    name: "Explosive High Knees",
    type: "cardio",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "butt-kickers-explosive",
    name: "Explosive Butt Kickers",
    type: "cardio",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Sport Specific
  {
    id: "lateral-shuffle-jump",
    name: "Lateral Shuffle Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "cone-hop",
    name: "Cone Hop",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "hexagon-jump",
    name: "Hexagon Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "ladder-hop",
    name: "Ladder Hop",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
];
