import type { ExercisesDocType } from "./exercises";

export const barbellExercises: ExercisesDocType[] = [
  {
    id: "barbell-squat",
    name: "Barbell Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell", "squatrack"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-deadlift",
    name: "Barbell Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-good-morning",
    name: "Barbell Good Morning",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-overhead-press",
    name: "Barbell Overhead Press",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-incline-bench-press",
    name: "Barbell Incline Bench Press",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell", "inclinebench"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["isolation"],
  },
  {
    id: "barbell-hip-thrust",
    name: "Barbell Hip Thrust",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-romanian-deadlift",
    name: "Barbell Romanian Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-stiff-leg-deadlift",
    name: "Barbell Stiff Leg Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-sumo-deadlift",
    name: "Barbell Sumo Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-front-squat",
    name: "Barbell Front Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell", "squatrack"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-hack-squat",
    name: "Barbell Hack Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-close-grip-bench-press",
    name: "Barbell Close Grip Bench Press",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-decline-bench-press",
    name: "Barbell Decline Bench Press",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell", "flatbench"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-bent-over-row",
    name: "Barbell Bent Over Row",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-pendlay-row",
    name: "Barbell Pendlay Row",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-upright-row",
    name: "Barbell Upright Row",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound"],
  },
  {
    id: "barbell-push-press",
    name: "Barbell Push Press",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-behind-neck-press",
    name: "Barbell Behind Neck Press",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound"],
  },
  {
    id: "barbell-high-pull",
    name: "Barbell High Pull",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-clean",
    name: "Barbell Clean",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-clean-and-press",
    name: "Barbell Clean and Press",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-snatch",
    name: "Barbell Snatch",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-thruster",
    name: "Barbell Thruster",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-shrug",
    name: "Barbell Shrug",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["isolation"],
  },
  {
    id: "barbell-calf-raise",
    name: "Barbell Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["isolation"],
  },
  {
    id: "barbell-lunge",
    name: "Barbell Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-reverse-lunge",
    name: "Barbell Reverse Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-walking-lunge",
    name: "Barbell Walking Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-split-squat",
    name: "Barbell Split Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-step-up",
    name: "Barbell Step Up",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "barbell-reverse-curl",
    name: "Barbell Reverse Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["isolation"],
  },
  {
    id: "barbell-wrist-curl",
    name: "Barbell Wrist Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell"],
    tags: ["isolation"],
  },
  {
    id: "barbell-preacher-curl",
    name: "Barbell Preacher Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["barbell", "flatbench"],
    tags: ["isolation"],
  },
];
