import { type ExercisesDocType } from "./exercises";

export const bandExercises: ExercisesDocType[] = [
  // Upper Body - Chest
  {
    id: "band-chest-press",
    name: "Band Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-chest-fly",
    name: "Band Chest Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-incline-chest-press",
    name: "Band Incline Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-decline-chest-press",
    name: "Band Decline Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-single-arm-chest-press",
    name: "Band Single Arm Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },

  // Upper Body - Back
  {
    id: "band-lat-pulldown",
    name: "Band Lat Pulldown",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-seated-row",
    name: "Band Seated Row",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-bent-over-row",
    name: "Band Bent Over Row",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-single-arm-row",
    name: "Band Single Arm Row",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-reverse-fly",
    name: "Band Reverse Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-face-pull",
    name: "Band Face Pull",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-high-row",
    name: "Band High Row",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-pull-apart",
    name: "Band Pull Apart",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },

  // Upper Body - Shoulders
  {
    id: "band-shoulder-press",
    name: "Band Shoulder Press",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-lateral-raise",
    name: "Band Lateral Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-front-raise",
    name: "Band Front Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-rear-delt-fly",
    name: "Band Rear Delt Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-upright-row",
    name: "Band Upright Row",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-arnold-press",
    name: "Band Arnold Press",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-external-rotation",
    name: "Band External Rotation",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-internal-rotation",
    name: "Band Internal Rotation",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },

  // Upper Body - Arms
  {
    id: "band-bicep-curl",
    name: "Band Bicep Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-hammer-curl",
    name: "Band Hammer Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-overhead-tricep-extension",
    name: "Band Overhead Tricep Extension",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-tricep-pushdown",
    name: "Band Tricep Pushdown",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-concentration-curl",
    name: "Band Concentration Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-21s-curl",
    name: "Band 21s Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-kickback",
    name: "Band Kickback",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },

  // Lower Body - Legs
  {
    id: "band-squat",
    name: "Band Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-goblet-squat",
    name: "Band Goblet Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-sumo-squat",
    name: "Band Sumo Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-bulgarian-split-squat",
    name: "Band Bulgarian Split Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-lunge",
    name: "Band Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-reverse-lunge",
    name: "Band Reverse Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-lateral-lunge",
    name: "Band Lateral Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-step-up",
    name: "Band Step Up",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-deadlift",
    name: "Band Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-romanian-deadlift",
    name: "Band Romanian Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-single-leg-deadlift",
    name: "Band Single Leg Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-calf-raise",
    name: "Band Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },

  // Lower Body - Glutes
  {
    id: "band-glute-bridge",
    name: "Band Glute Bridge",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-hip-thrust",
    name: "Band Hip Thrust",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-clamshell",
    name: "Band Clamshell",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-lateral-walk",
    name: "Band Lateral Walk",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-monster-walk",
    name: "Band Monster Walk",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-fire-hydrant",
    name: "Band Fire Hydrant",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-donkey-kick",
    name: "Band Donkey Kick",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-kickback-standing",
    name: "Band Kickback Standing",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },

  // Core
  {
    id: "band-pallof-press",
    name: "Band Pallof Press",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-woodchop",
    name: "Band Woodchop",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-russian-twist",
    name: "Band Russian Twist",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-bicycle-crunch",
    name: "Band Bicycle Crunch",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-standing-oblique-crunch",
    name: "Band Standing Oblique Crunch",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["isolation"],
  },

  // Full Body
  {
    id: "band-thruster",
    name: "Band Thruster",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-burpee-with-press",
    name: "Band Burpee with Press",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-clean-and-press",
    name: "Band Clean and Press",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-high-pull",
    name: "Band High Pull",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },

  // Mobility/Stretching
  {
    id: "band-shoulder-dislocate",
    name: "Band Shoulder Dislocate",
    type: "mobility",
    track: ["time"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-hip-flexor-stretch",
    name: "Band Hip Flexor Stretch",
    type: "stretching",
    track: ["time"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-hamstring-stretch",
    name: "Band Hamstring Stretch",
    type: "stretching",
    track: ["time"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-chest-stretch",
    name: "Band Chest Stretch",
    type: "stretching",
    track: ["time"],
    equipment: ["band"],
    tags: ["isolation"],
  },
  {
    id: "band-lat-stretch",
    name: "Band Lat Stretch",
    type: "stretching",
    track: ["time"],
    equipment: ["band"],
    tags: ["isolation"],
  },

  // Advanced/Sport-Specific
  {
    id: "band-assisted-pull-up",
    name: "Band Assisted Pull Up",
    type: "strength",
    track: ["weight"],
    equipment: ["band", "pullupbar"],
    tags: ["compound"],
  },
  {
    id: "band-resisted-sprint",
    name: "Band Resisted Sprint",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-jump-squat",
    name: "Band Jump Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["band"],
    tags: ["compound"],
  },
  {
    id: "band-speed-punch",
    name: "Band Speed Punch",
    type: "cardio",
    track: ["time"],
    equipment: ["band"],
    tags: ["compound"],
  },
];
