import { type ExercisesDocType } from "./exercises";

export const cardioEquipmentExercises: ExercisesDocType[] = [
  // Treadmill Workouts
  {
    id: "treadmill-walk",
    name: "Treadmill Walk",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["treadmill"],
    tags: ["compound", "primary"],
  },
  {
    id: "treadmill-jog",
    name: "Treadmill Jog",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["treadmill"],
    tags: ["compound", "primary"],
  },
  {
    id: "treadmill-run",
    name: "Treadmill Run",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["treadmill"],
    tags: ["compound", "primary"],
  },
  {
    id: "treadmill-sprint-intervals",
    name: "Treadmill Sprint Intervals",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["treadmill"],
    tags: ["compound"],
  },
  {
    id: "treadmill-incline-walk",
    name: "Treadmill Incline Walk",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["treadmill"],
    tags: ["compound"],
  },
  {
    id: "treadmill-hill-intervals",
    name: "Treadmill Hill Intervals",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["treadmill"],
    tags: ["compound"],
  },
  {
    id: "treadmill-pyramid-workout",
    name: "Treadmill Pyramid Workout",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["treadmill"],
    tags: ["compound"],
  },

  // Stationary Bike Workouts
  {
    id: "bike-steady-state",
    name: "Stationary Bike Steady State",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["bike"],
    tags: ["compound", "primary"],
  },
  {
    id: "bike-intervals",
    name: "Stationary Bike Intervals",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["bike"],
    tags: ["compound"],
  },
  {
    id: "bike-hill-climb",
    name: "Stationary Bike Hill Climb",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["bike"],
    tags: ["compound"],
  },
  {
    id: "bike-tabata",
    name: "Stationary Bike Tabata",
    type: "cardio",
    track: ["time"],
    equipment: ["bike"],
    tags: ["compound"],
  },
  {
    id: "bike-spinning",
    name: "Spinning Class",
    type: "cardio",
    track: ["time"],
    equipment: ["bike"],
    tags: ["compound"],
  },
  {
    id: "bike-recovery-ride",
    name: "Recovery Ride",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["bike"],
    tags: ["compound"],
  },

  // Elliptical Workouts
  {
    id: "elliptical-steady-state",
    name: "Elliptical Steady State",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["elliptical"],
    tags: ["compound", "primary"],
  },
  {
    id: "elliptical-intervals",
    name: "Elliptical Intervals",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["elliptical"],
    tags: ["compound"],
  },
  {
    id: "elliptical-reverse",
    name: "Elliptical Reverse",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["elliptical"],
    tags: ["compound"],
  },
  {
    id: "elliptical-arms-only",
    name: "Elliptical Arms Only",
    type: "cardio",
    track: ["time"],
    equipment: ["elliptical"],
    tags: ["compound"],
  },
  {
    id: "elliptical-legs-only",
    name: "Elliptical Legs Only",
    type: "cardio",
    track: ["time"],
    equipment: ["elliptical"],
    tags: ["compound"],
  },
  {
    id: "elliptical-hiit",
    name: "Elliptical HIIT",
    type: "cardio",
    track: ["time"],
    equipment: ["elliptical"],
    tags: ["compound"],
  },

  // Rowing Machine Workouts
  {
    id: "rowing-steady-state",
    name: "Rowing Steady State",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["rower"],
    tags: ["compound", "primary"],
  },
  {
    id: "rowing-intervals",
    name: "Rowing Intervals",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["rower"],
    tags: ["compound"],
  },
  {
    id: "rowing-pyramid",
    name: "Rowing Pyramid",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["rower"],
    tags: ["compound"],
  },
  {
    id: "rowing-500m-repeats",
    name: "500m Rowing Repeats",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["rower"],
    tags: ["compound"],
  },
  {
    id: "rowing-2k-test",
    name: "2K Rowing Test",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["rower"],
    tags: ["compound"],
  },
  {
    id: "rowing-power-strokes",
    name: "Rowing Power Strokes",
    type: "cardio",
    track: ["time"],
    equipment: ["rower"],
    tags: ["compound"],
  },
  {
    id: "rowing-endurance",
    name: "Rowing Endurance",
    type: "cardio",
    track: ["time", "distance"],
    equipment: ["rower"],
    tags: ["compound"],
  },

  // StairMaster Workouts
  {
    id: "stairmaster-steady-climb",
    name: "StairMaster Steady Climb",
    type: "cardio",
    track: ["time"],
    equipment: ["stairmaster"],
    tags: ["compound", "primary"],
  },
  {
    id: "stairmaster-intervals",
    name: "StairMaster Intervals",
    type: "cardio",
    track: ["time"],
    equipment: ["stairmaster"],
    tags: ["compound"],
  },
  {
    id: "stairmaster-side-steps",
    name: "StairMaster Side Steps",
    type: "cardio",
    track: ["time"],
    equipment: ["stairmaster"],
    tags: ["compound"],
  },
  {
    id: "stairmaster-double-steps",
    name: "StairMaster Double Steps",
    type: "cardio",
    track: ["time"],
    equipment: ["stairmaster"],
    tags: ["compound"],
  },
  {
    id: "stairmaster-crossover-steps",
    name: "StairMaster Crossover Steps",
    type: "cardio",
    track: ["time"],
    equipment: ["stairmaster"],
    tags: ["compound"],
  },

  // Jump Rope Workouts
  {
    id: "jump-rope-basic",
    name: "Basic Jump Rope",
    type: "cardio",
    track: ["time"],
    equipment: ["jumprope"],
    tags: ["compound", "primary"],
  },
  {
    id: "jump-rope-double-unders",
    name: "Double Unders",
    type: "cardio",
    track: ["time"],
    equipment: ["jumprope"],
    tags: ["compound"],
  },
  {
    id: "jump-rope-single-leg",
    name: "Single Leg Jump Rope",
    type: "cardio",
    track: ["time"],
    equipment: ["jumprope"],
    tags: ["compound"],
  },
  {
    id: "jump-rope-criss-cross",
    name: "Criss Cross Jump Rope",
    type: "cardio",
    track: ["time"],
    equipment: ["jumprope"],
    tags: ["compound"],
  },
  {
    id: "jump-rope-boxer-step",
    name: "Boxer Step Jump Rope",
    type: "cardio",
    track: ["time"],
    equipment: ["jumprope"],
    tags: ["compound"],
  },
  {
    id: "jump-rope-high-knees",
    name: "High Knees Jump Rope",
    type: "cardio",
    track: ["time"],
    equipment: ["jumprope"],
    tags: ["compound"],
  },
  {
    id: "jump-rope-side-swing",
    name: "Side Swing Jump Rope",
    type: "cardio",
    track: ["time"],
    equipment: ["jumprope"],
    tags: ["compound"],
  },
  {
    id: "jump-rope-alternating-foot",
    name: "Alternating Foot Jump Rope",
    type: "cardio",
    track: ["time"],
    equipment: ["jumprope"],
    tags: ["compound"],
  },

  // Cross-Training Cardio
  {
    id: "cardio-circuit-training",
    name: "Cardio Circuit Training",
    type: "cardio",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "hiit-cardio-mix",
    name: "HIIT Cardio Mix",
    type: "cardio",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "tabata-cardio",
    name: "Tabata Cardio",
    type: "cardio",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "emom-cardio",
    name: "EMOM Cardio",
    type: "cardio",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
];
