import type { ExercisesDocType } from "./exercises";

export const cableExercises: ExercisesDocType[] = [
  {
    id: "cable-lat-pulldown",
    name: "Cable Lat Pulldown",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-seated-row",
    name: "Cable Seated Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-tricep-pushdown",
    name: "Cable Tricep Pushdown",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-bicep-curl",
    name: "Cable Bicep Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-chest-fly",
    name: "Cable Chest Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-crossover",
    name: "Cable Crossover",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-front-raise",
    name: "Cable Front Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-rear-delt-fly",
    name: "Cable Rear Delt Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-face-pull",
    name: "Cable Face Pull",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "cable-upright-row",
    name: "Cable Upright Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "cable-shrug",
    name: "Cable Shrug",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-overhead-press",
    name: "Cable Overhead Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-chest-press",
    name: "Cable Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-incline-chest-press",
    name: "Cable Incline Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-decline-chest-press",
    name: "Cable Decline Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-single-arm-row",
    name: "Cable Single Arm Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-high-row",
    name: "Cable High Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-low-row",
    name: "Cable Low Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-hammer-curl",
    name: "Cable Hammer Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-preacher-curl",
    name: "Cable Preacher Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-concentration-curl",
    name: "Cable Concentration Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-reverse-curl",
    name: "Cable Reverse Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-bayesian-curl",
    name: "Cable Bayesian Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-overhead-tricep-extension",
    name: "Cable Overhead Tricep Extension",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-tricep-kickback",
    name: "Cable Tricep Kickback",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-rope-tricep-pushdown",
    name: "Cable Rope Tricep Pushdown",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-straight-bar-tricep-pushdown",
    name: "Cable Straight Bar Tricep Pushdown",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-v-bar-tricep-pushdown",
    name: "Cable V-Bar Tricep Pushdown",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-wood-chop",
    name: "Cable Wood Chop",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "cable-pallof-press",
    name: "Cable Pallof Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "cable-russian-twist",
    name: "Cable Russian Twist",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-reverse-fly",
    name: "Cable Reverse Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-straight-arm-pulldown",
    name: "Cable Straight Arm Pulldown",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-pullover",
    name: "Cable Pullover",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "cable-squat",
    name: "Cable Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-lunge",
    name: "Cable Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-lateral-lunge",
    name: "Cable Lateral Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "cable-hip-abduction",
    name: "Cable Hip Abduction",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-hip-adduction",
    name: "Cable Hip Adduction",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-glute-kickback",
    name: "Cable Glute Kickback",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-leg-extension",
    name: "Cable Leg Extension",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-leg-curl",
    name: "Cable Leg Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-calf-raise",
    name: "Cable Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "cable-standing-calf-raise",
    name: "Cable Standing Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
];
