import type { ExercisesDocType } from "./exercises";

export const bodyweightExercises: ExercisesDocType[] = [
  {
    id: "push-up",
    name: "Push-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "diamond-push-up",
    name: "Diamond Push-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "wide-grip-push-up",
    name: "Wide Grip Push-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "incline-push-up",
    name: "Incline Push-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "decline-push-up",
    name: "Decline Push-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "pike-push-up",
    name: "Pike Push-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "archer-push-up",
    name: "Archer Push-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "one-arm-push-up",
    name: "One Arm Push-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "handstand-push-up",
    name: "Handstand Push-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },

  {
    id: "pistol-squat",
    name: "Pistol Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "cossack-squat",
    name: "Cossack Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "bodyweight-lunge",
    name: "Bodyweight Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "walking-lunge",
    name: "Walking Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "lateral-lunge",
    name: "Lateral Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "curtsy-lunge",
    name: "Curtsy Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "single-leg-deadlift",
    name: "Single Leg Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "single-leg-glute-bridge",
    name: "Single Leg Glute Bridge",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "single-leg-hip-thrust",
    name: "Single Leg Hip Thrust",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "single-leg-calf-raise",
    name: "Single Leg Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },

  {
    id: "plank",
    name: "Plank",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "side-plank",
    name: "Side Plank",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "plank-up-down",
    name: "Plank Up-Down",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "burpee",
    name: "Burpee",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "burpee-with-jump",
    name: "Burpee with Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },

  {
    id: "sit-up",
    name: "Sit-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "crunch",
    name: "Crunch",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "reverse-crunch",
    name: "Reverse Crunch",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "leg-raise",
    name: "Leg Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "flutter-kick",
    name: "Flutter Kick",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "scissor-kick",
    name: "Scissor Kick",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["isolation"],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "superman",
    name: "Superman",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "back-extension",
    name: "Back Extension",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "good-morning",
    name: "Good Morning",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "hyperextension",
    name: "Hyperextension",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "tricep-dip",
    name: "Tricep Dip",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "bench-dip",
    name: "Bench Dip",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "chair-dip",
    name: "Chair Dip",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "chin-up",
    name: "Chin-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "wide-grip-pull-up",
    name: "Wide Grip Pull-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "neutral-grip-pull-up",
    name: "Neutral Grip Pull-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "commando-pull-up",
    name: "Commando Pull-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "muscle-up",
    name: "Muscle-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "l-sit",
    name: "L-Sit",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "human-flag",
    name: "Human Flag",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "front-lever",
    name: "Front Lever",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "back-lever",
    name: "Back Lever",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "handstand",
    name: "Handstand",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "crow-pose",
    name: "Crow Pose",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "planche",
    name: "Planche",
    type: "strength",
    track: ["time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "jumping-jack",
    name: "Jumping Jack",
    type: "cardio",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "high-knee",
    name: "High Knee",
    type: "cardio",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "butt-kick",
    name: "Butt Kick",
    type: "cardio",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  {
    id: "step-up",
    name: "Step-up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
];
