import type { ExercisesDocType } from "./exercises";

export const machineExercises: ExercisesDocType[] = [
  {
    id: "leg-curl",
    name: "Leg Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-incline-chest-press",
    name: "Machine Incline Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-decline-chest-press",
    name: "Machine Decline Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-chest-fly",
    name: "Machine Chest Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-lateral-raise",
    name: "Machine Lateral Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-rear-delt-fly",
    name: "Machine Rear Delt Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-leg-extension",
    name: "Machine Leg Extension",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-leg-curl-lying",
    name: "Machine Leg Curl (Lying)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-leg-curl-seated",
    name: "Machine Leg Curl (Seated)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-leg-curl-standing",
    name: "Machine Leg Curl (Standing)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-hack-squat",
    name: "Machine Hack Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-smith-squat",
    name: "Machine Smith Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-smith-bench-press",
    name: "Machine Smith Bench Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-smith-incline-bench-press",
    name: "Machine Smith Incline Bench Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-smith-row",
    name: "Machine Smith Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-smith-overhead-press",
    name: "Machine Smith Overhead Press",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-smith-calf-raise",
    name: "Machine Smith Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-hip-abductor",
    name: "Machine Hip Abductor",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-hip-adductor",
    name: "Machine Hip Adductor",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-glute-bridge",
    name: "Machine Glute Bridge",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-seated-calf-raise",
    name: "Machine Seated Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-standing-calf-raise",
    name: "Machine Standing Calf Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-preacher-curl",
    name: "Machine Preacher Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-bicep-curl",
    name: "Machine Bicep Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-tricep-dip",
    name: "Machine Tricep Dip",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "machine-tricep-extension",
    name: "Machine Tricep Extension",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-pullover",
    name: "Machine Pullover",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "machine-back-extension",
    name: "Machine Back Extension",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "machine-ab-crunch",
    name: "Machine Ab Crunch",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-oblique-crunch",
    name: "Machine Oblique Crunch",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-torso-rotation",
    name: "Machine Torso Rotation",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "machine-assisted-pullup",
    name: "Machine Assisted Pull-up",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-assisted-dip",
    name: "Machine Assisted Dip",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "machine-t-bar-row",
    name: "Machine T-Bar Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-shrug",
    name: "Machine Shrug",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-upright-row",
    name: "Machine Upright Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "machine-reverse-fly",
    name: "Machine Reverse Fly",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-leg-press-45-degree",
    name: "Machine Leg Press (45 Degree)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-leg-press-horizontal",
    name: "Machine Leg Press (Horizontal)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-leg-press-vertical",
    name: "Machine Leg Press (Vertical)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-sissy-squat",
    name: "Machine Sissy Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-pendulum-squat",
    name: "Machine Pendulum Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-belt-squat",
    name: "Machine Belt Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-seated-row-wide-grip",
    name: "Machine Seated Row (Wide Grip)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-seated-row-narrow-grip",
    name: "Machine Seated Row (Narrow Grip)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-lat-pulldown-wide-grip",
    name: "Machine Lat Pulldown (Wide Grip)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-lat-pulldown-narrow-grip",
    name: "Machine Lat Pulldown (Narrow Grip)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-lat-pulldown-reverse-grip",
    name: "Machine Lat Pulldown (Reverse Grip)",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-high-row",
    name: "Machine High Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-low-row",
    name: "Machine Low Row",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-reverse-hyperextension",
    name: "Machine Reverse Hyperextension",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound"],
  },
  {
    id: "machine-glute-ham-raise",
    name: "Machine Glute Ham Raise",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-nordic-curl",
    name: "Machine Nordic Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["compound", "primary"],
  },
  {
    id: "machine-wrist-curl",
    name: "Machine Wrist Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
  {
    id: "machine-reverse-wrist-curl",
    name: "Machine Reverse Wrist Curl",
    type: "strength",
    track: ["weight"],
    equipment: ["machine"],
    tags: ["isolation"],
  },
];
