import { type ExercisesDocType } from "./exercises";

export const kettlebellExercises: ExercisesDocType[] = [
  // Fundamental Kettlebell Movements
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound", "primary"],
  },
  {
    id: "kettlebell-deadlift",
    name: "Kettlebell Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound", "primary"],
  },
  {
    id: "kettlebell-goblet-squat",
    name: "Kettlebell Goblet Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound", "primary"],
  },
  {
    id: "kettlebell-turkish-get-up",
    name: "Turkish Get Up",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },

  // Upper Body
  {
    id: "kettlebell-press",
    name: "Kettlebell Press",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-single-arm-press",
    name: "Kettlebell Single Arm Press",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-clean-and-press",
    name: "Kettlebell Clean and Press",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-snatch",
    name: "Kettlebell Snatch",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-clean",
    name: "Kettlebell Clean",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-high-pull",
    name: "Kettlebell High Pull",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-upright-row",
    name: "Kettlebell Upright Row",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-bent-over-row",
    name: "Kettlebell Bent Over Row",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-single-arm-row",
    name: "Kettlebell Single Arm Row",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-chest-press",
    name: "Kettlebell Chest Press",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-floor-press",
    name: "Kettlebell Floor Press",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },

  // Lower Body
  {
    id: "kettlebell-sumo-deadlift",
    name: "Kettlebell Sumo Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-single-leg-deadlift",
    name: "Kettlebell Single Leg Deadlift",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-lunge",
    name: "Kettlebell Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-reverse-lunge",
    name: "Kettlebell Reverse Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-lateral-lunge",
    name: "Kettlebell Lateral Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-cossack-squat",
    name: "Kettlebell Cossack Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-pistol-squat",
    name: "Kettlebell Pistol Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-step-up",
    name: "Kettlebell Step Up",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },

  // Core & Functional
  {
    id: "kettlebell-windmill",
    name: "Kettlebell Windmill",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-around-the-world",
    name: "Kettlebell Around the World",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["isolation"],
  },
  {
    id: "kettlebell-figure-8",
    name: "Kettlebell Figure 8",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-halo",
    name: "Kettlebell Halo",
    type: "mobility",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["isolation"],
  },
  {
    id: "kettlebell-russian-twist",
    name: "Kettlebell Russian Twist",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["isolation"],
  },
  {
    id: "kettlebell-woodchop",
    name: "Kettlebell Woodchop",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },

  // Carries & Walks
  {
    id: "kettlebell-farmers-walk",
    name: "Kettlebell Farmers Walk",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-suitcase-carry",
    name: "Kettlebell Suitcase Carry",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-overhead-carry",
    name: "Kettlebell Overhead Carry",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-front-loaded-carry",
    name: "Kettlebell Front Loaded Carry",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-racked-carry",
    name: "Kettlebell Racked Carry",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },

  // Ballistic Movements
  {
    id: "kettlebell-american-swing",
    name: "Kettlebell American Swing",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-single-arm-swing",
    name: "Kettlebell Single Arm Swing",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-alternating-swing",
    name: "Kettlebell Alternating Swing",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "kettlebell-thruster",
    name: "Kettlebell Thruster",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
];
