import { type ExercisesDocType } from "./exercises";

export const functionalExercises: ExercisesDocType[] = [
  // Sled Exercises
  {
    id: "sled-push",
    name: "Sled Push",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["sled"],
    tags: ["compound", "primary"],
  },
  {
    id: "sled-pull",
    name: "Sled Pull",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["sled"],
    tags: ["compound", "primary"],
  },
  {
    id: "sled-drag-backward",
    name: "Sled Drag Backward",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["sled"],
    tags: ["compound"],
  },
  {
    id: "sled-lateral-drag",
    name: "Sled Lateral Drag",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["sled"],
    tags: ["compound"],
  },
  {
    id: "sled-sprint",
    name: "Sled Sprint",
    type: "cardio",
    track: ["weight", "distance", "time"],
    equipment: ["sled"],
    tags: ["compound"],
  },
  {
    id: "sled-bear-crawl",
    name: "Sled Bear Crawl",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["sled"],
    tags: ["compound"],
  },

  // Battle Rope Exercises
  {
    id: "battle-rope-waves",
    name: "Battle Rope Waves",
    type: "cardio",
    track: ["time"],
    equipment: ["battlerope"],
    tags: ["compound", "primary"],
  },
  {
    id: "battle-rope-alternating-waves",
    name: "Battle Rope Alternating Waves",
    type: "cardio",
    track: ["time"],
    equipment: ["battlerope"],
    tags: ["compound"],
  },
  {
    id: "battle-rope-slams",
    name: "Battle Rope Slams",
    type: "strength",
    track: ["time"],
    equipment: ["battlerope"],
    tags: ["compound"],
  },
  {
    id: "battle-rope-spirals",
    name: "Battle Rope Spirals",
    type: "cardio",
    track: ["time"],
    equipment: ["battlerope"],
    tags: ["compound"],
  },
  {
    id: "battle-rope-side-slams",
    name: "Battle Rope Side Slams",
    type: "strength",
    track: ["time"],
    equipment: ["battlerope"],
    tags: ["compound"],
  },
  {
    id: "battle-rope-jumping-jacks",
    name: "Battle Rope Jumping Jacks",
    type: "cardio",
    track: ["time"],
    equipment: ["battlerope"],
    tags: ["compound"],
  },
  {
    id: "battle-rope-grappler-toss",
    name: "Battle Rope Grappler Toss",
    type: "strength",
    track: ["time"],
    equipment: ["battlerope"],
    tags: ["compound"],
  },
  {
    id: "battle-rope-russian-twist",
    name: "Battle Rope Russian Twist",
    type: "strength",
    track: ["time"],
    equipment: ["battlerope"],
    tags: ["compound"],
  },
  {
    id: "battle-rope-burpee",
    name: "Battle Rope Burpee",
    type: "strength",
    track: ["time"],
    equipment: ["battlerope"],
    tags: ["compound"],
  },

  // Tire Exercises
  {
    id: "tire-flip",
    name: "Tire Flip",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["tire"],
    tags: ["compound", "primary"],
  },
  {
    id: "tire-sledgehammer-strike",
    name: "Tire Sledgehammer Strike",
    type: "strength",
    track: ["time"],
    equipment: ["tire"],
    tags: ["compound"],
  },
  {
    id: "tire-jump",
    name: "Tire Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["tire"],
    tags: ["compound"],
  },
  {
    id: "tire-step-up",
    name: "Tire Step Up",
    type: "strength",
    track: ["weight"],
    equipment: ["tire"],
    tags: ["compound"],
  },
  {
    id: "tire-box-jump",
    name: "Tire Box Jump",
    type: "strength",
    track: ["weight"],
    equipment: ["tire"],
    tags: ["compound"],
  },
  {
    id: "tire-bear-crawl",
    name: "Tire Bear Crawl",
    type: "strength",
    track: ["distance"],
    equipment: ["tire"],
    tags: ["compound"],
  },
  {
    id: "tire-mountain-climber",
    name: "Tire Mountain Climber",
    type: "cardio",
    track: ["time"],
    equipment: ["tire"],
    tags: ["compound"],
  },
  {
    id: "tire-incline-push-up",
    name: "Tire Incline Push Up",
    type: "strength",
    track: ["weight"],
    equipment: ["tire"],
    tags: ["compound"],
  },

  // Farmers Walk Variations
  {
    id: "farmers-walk-dumbbell",
    name: "Farmers Walk (Dumbbell)",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["dumbbell"],
    tags: ["compound", "primary"],
  },
  {
    id: "farmers-walk-kettlebell",
    name: "Farmers Walk (Kettlebell)",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "farmers-walk-barbell",
    name: "Farmers Walk (Barbell)",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["barbell"],
    tags: ["compound"],
  },
  {
    id: "suitcase-carry-dumbbell",
    name: "Suitcase Carry (Dumbbell)",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },
  {
    id: "overhead-carry-dumbbell",
    name: "Overhead Carry (Dumbbell)",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },
  {
    id: "front-rack-carry",
    name: "Front Rack Carry",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },
  {
    id: "offset-farmers-walk",
    name: "Offset Farmers Walk",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },

  // Functional Movement Patterns
  {
    id: "bear-crawl",
    name: "Bear Crawl",
    type: "strength",
    track: ["distance", "time"],
    equipment: ["bodyweight"],
    tags: ["compound", "primary"],
  },
  {
    id: "crab-walk",
    name: "Crab Walk",
    type: "strength",
    track: ["distance", "time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "duck-walk",
    name: "Duck Walk",
    type: "strength",
    track: ["distance", "time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "lizard-crawl",
    name: "Lizard Crawl",
    type: "strength",
    track: ["distance", "time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "army-crawl",
    name: "Army Crawl",
    type: "strength",
    track: ["distance", "time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "inch-worm",
    name: "Inch Worm",
    type: "strength",
    track: ["distance"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Strongman Movements
  {
    id: "atlas-stone-lift",
    name: "Atlas Stone Lift",
    type: "strength",
    track: ["weight"],
    equipment: ["other"],
    tags: ["compound"],
  },
  {
    id: "log-press",
    name: "Log Press",
    type: "strength",
    track: ["weight"],
    equipment: ["other"],
    tags: ["compound"],
  },
  {
    id: "yoke-walk",
    name: "Yoke Walk",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["other"],
    tags: ["compound"],
  },
  {
    id: "truck-pull",
    name: "Truck Pull",
    type: "strength",
    track: ["distance", "time"],
    equipment: ["other"],
    tags: ["compound"],
  },
  {
    id: "keg-carry",
    name: "Keg Carry",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["other"],
    tags: ["compound"],
  },
  {
    id: "sandbag-carry",
    name: "Sandbag Carry",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["other"],
    tags: ["compound"],
  },
  {
    id: "sandbag-throw",
    name: "Sandbag Throw",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["other"],
    tags: ["compound"],
  },

  // Multi-Tool Functional
  {
    id: "man-maker-dumbbell",
    name: "Man Maker (Dumbbell)",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },
  {
    id: "man-maker-kettlebell",
    name: "Man Maker (Kettlebell)",
    type: "strength",
    track: ["weight"],
    equipment: ["kettlebell"],
    tags: ["compound"],
  },
  {
    id: "devil-press",
    name: "Devil Press",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },
  {
    id: "turkish-get-up-dumbbell",
    name: "Turkish Get Up (Dumbbell)",
    type: "strength",
    track: ["weight"],
    equipment: ["dumbbell"],
    tags: ["compound"],
  },
  {
    id: "get-up-sit-up",
    name: "Get Up Sit Up",
    type: "strength",
    track: ["weight"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },

  // Outdoor/Natural Movement
  {
    id: "log-carry",
    name: "Log Carry",
    type: "strength",
    track: ["distance", "time"],
    equipment: ["other"],
    tags: ["compound"],
  },
  {
    id: "rock-carry",
    name: "Rock Carry",
    type: "strength",
    track: ["distance", "time"],
    equipment: ["other"],
    tags: ["compound"],
  },
  {
    id: "tree-pull-up",
    name: "Tree Pull Up",
    type: "strength",
    track: ["weight"],
    equipment: ["other"],
    tags: ["compound"],
  },
  {
    id: "hill-sprint",
    name: "Hill Sprint",
    type: "cardio",
    track: ["distance", "time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
  {
    id: "sand-run",
    name: "Sand Run",
    type: "cardio",
    track: ["distance", "time"],
    equipment: ["bodyweight"],
    tags: ["compound"],
  },
];
