import { type ExercisesDocType } from "./exercises";

export const medicineballExercises: ExercisesDocType[] = [
  // Core Fundamentals
  {
    id: "medicine-ball-slam",
    name: "Medicine Ball Slam",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound", "primary"],
  },
  {
    id: "medicine-ball-wall-ball",
    name: "Wall Ball",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound", "primary"],
  },
  {
    id: "medicine-ball-russian-twist",
    name: "Medicine Ball Russian Twist",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["isolation"],
  },
  {
    id: "medicine-ball-sit-up",
    name: "Medicine Ball Sit Up",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["isolation"],
  },

  // Upper Body Throws
  {
    id: "medicine-ball-chest-pass",
    name: "Medicine Ball Chest Pass",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-overhead-throw",
    name: "Medicine Ball Overhead Throw",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-granny-toss",
    name: "Medicine Ball Granny Toss",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-chest-throw",
    name: "Medicine Ball Chest Throw",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-single-arm-throw",
    name: "Medicine Ball Single Arm Throw",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },

  // Rotational Movements
  {
    id: "medicine-ball-rotational-throw",
    name: "Medicine Ball Rotational Throw",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-side-throw",
    name: "Medicine Ball Side Throw",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-woodchop",
    name: "Medicine Ball Woodchop",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-rainbow-slam",
    name: "Medicine Ball Rainbow Slam",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-diagonal-chop",
    name: "Medicine Ball Diagonal Chop",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },

  // Lower Body
  {
    id: "medicine-ball-squat",
    name: "Medicine Ball Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-goblet-squat",
    name: "Medicine Ball Goblet Squat",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-lunge",
    name: "Medicine Ball Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-reverse-lunge",
    name: "Medicine Ball Reverse Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-lateral-lunge",
    name: "Medicine Ball Lateral Lunge",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-step-up",
    name: "Medicine Ball Step Up",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },

  // Core & Stability
  {
    id: "medicine-ball-v-up",
    name: "Medicine Ball V-Up",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["isolation"],
  },
  {
    id: "medicine-ball-bicycle-crunch",
    name: "Medicine Ball Bicycle Crunch",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["isolation"],
  },
  {
    id: "medicine-ball-plank-rollout",
    name: "Medicine Ball Plank Rollout",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-dead-bug",
    name: "Medicine Ball Dead Bug",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["isolation"],
  },
  {
    id: "medicine-ball-mountain-climber",
    name: "Medicine Ball Mountain Climber",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-bear-crawl",
    name: "Medicine Ball Bear Crawl",
    type: "strength",
    track: ["weight", "distance"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },

  // Full Body
  {
    id: "medicine-ball-burpee",
    name: "Medicine Ball Burpee",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-thruster",
    name: "Medicine Ball Thruster",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-clean",
    name: "Medicine Ball Clean",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-turkish-get-up",
    name: "Medicine Ball Turkish Get Up",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },

  // Partner Exercises
  {
    id: "medicine-ball-partner-toss",
    name: "Medicine Ball Partner Toss",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-partner-rotation",
    name: "Medicine Ball Partner Rotation",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-partner-sit-up-pass",
    name: "Medicine Ball Partner Sit Up Pass",
    type: "strength",
    track: ["weight"],
    equipment: ["medicineball"],
    tags: ["isolation"],
  },

  // Cardio/Conditioning
  {
    id: "medicine-ball-slam-burpee",
    name: "Medicine Ball Slam Burpee",
    type: "cardio",
    track: ["weight", "time"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
  {
    id: "medicine-ball-tabata-slam",
    name: "Medicine Ball Tabata Slam",
    type: "cardio",
    track: ["weight", "time"],
    equipment: ["medicineball"],
    tags: ["compound"],
  },
];
