import type { TemplatesDocType } from "./templates";

export const fiveBy5TemplatesData: TemplatesDocType[] = [
  {
    id: "5x5-squat-a-1",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-squat",
    order: 1,
    load: 1.0, // 100% of max for working set
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1, // every workout
      },
      decrement: {
        value: 0.1, // 10% deload
        kind: "weight",
        type: "percentage",
        frequency: 3, // after 3 failed attempts
      },
    },
  },
  {
    id: "5x5-squat-a-2",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-squat",
    order: 2,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-squat-a-3",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-squat",
    order: 3,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-squat-a-4",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-squat",
    order: 4,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-squat-a-5",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-squat",
    order: 5,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-bench-a-1",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-bench-press",
    order: 6,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-bench-a-2",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-bench-press",
    order: 7,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-bench-a-3",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-bench-press",
    order: 8,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-bench-a-4",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-bench-press",
    order: 9,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-bench-a-5",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-bench-press",
    order: 10,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-row-a-1",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-row",
    order: 11,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-row-a-2",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-row",
    order: 12,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-row-a-3",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-row",
    order: 13,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-row-a-4",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-row",
    order: 14,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-row-a-5",
    programId: "5x5",
    routineId: "5x5-routine-a",
    exerciseId: "barbell-row",
    order: 15,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-squat-b-1",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-squat",
    order: 1,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-squat-b-2",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-squat",
    order: 2,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-squat-b-3",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-squat",
    order: 3,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-squat-b-4",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-squat",
    order: 4,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-squat-b-5",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-squat",
    order: 5,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-ohp-b-1",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-overhead-press",
    order: 6,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-ohp-b-2",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-overhead-press",
    order: 7,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-ohp-b-3",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-overhead-press",
    order: 8,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-ohp-b-4",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-overhead-press",
    order: 9,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-ohp-b-5",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-overhead-press",
    order: 10,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 5,
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
  {
    id: "5x5-deadlift-b-1",
    programId: "5x5",
    routineId: "5x5-routine-b",
    exerciseId: "barbell-deadlift",
    order: 11,
    load: 1.0,
    reps: 5,
    progression: {
      increment: {
        value: 10, // Deadlift progresses by 10 lbs
        kind: "weight",
        type: "absolute",
        frequency: 1,
      },
      decrement: {
        value: 0.1,
        kind: "weight",
        type: "percentage",
        frequency: 3,
      },
    },
  },
];
