import type { MyDatabase } from "./db";
import type { TemplatesDocType } from "./templates";

export async function init531HypertrophyTemplates(db: MyDatabase) {
  const templates: Array<TemplatesDocType> = [
    {
      id: "hQ8w2e9r4t5y6u7i8o1p0az",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-1",
      exerciseId: "barbell-overhead-press",
      order: 1,
      load: 0.65,
      reps: 5,
    },
    {
      id: "mZ2xVb7Lp9Qw3Er1Tg6Yh5N",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-1",
      exerciseId: "barbell-overhead-press",
      order: 2,
      load: 0.75,
      reps: 5,
    },
    {
      id: "Jk5Lm8Qw2Zx1Vb3Er7Tg4Q",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-1",
      exerciseId: "barbell-overhead-press",
      order: 3,
      load: 0.85,
      reps: 5,
    },
    {
      id: "Er6Tg2Yh9Nq3Wb5Lp8Zx1R",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-2",
      exerciseId: "barbell-deadlift",
      order: 1,
      load: 0.65,
      reps: 5,
    },
    {
      id: "Lp7Zx1Vb3Er6Tg2Yh9Nq5S",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-2",
      exerciseId: "barbell-deadlift",
      order: 2,
      load: 0.75,
      reps: 5,
    },
    {
      id: "Yh9Nq3Wb5Lp8Zx1Vb2Er6T",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-2",
      exerciseId: "barbell-deadlift",
      order: 3,
      load: 0.85,
      reps: 5,
    },
    {
      id: "Nq5Wb7Lp9Zx2Vb3Er6Tg1U",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-3",
      exerciseId: "barbell-bench-press",
      order: 1,
      load: 0.65,
      reps: 5,
    },
    {
      id: "Tg4Nq7Wb2Lp8Zx1Vb3Er6V",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-3",
      exerciseId: "barbell-bench-press",
      order: 2,
      load: 0.75,
      reps: 5,
    },
    {
      id: "Vb3Er6Tg2Yh9Nq5Wb7Lp8W",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-3",
      exerciseId: "barbell-bench-press",
      order: 3,
      load: 0.85,
      reps: 5,
    },
    {
      id: "Zx1Vb3Er6Tg2Yh9Nq5Wb7X",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-4",
      exerciseId: "barbell-squat",
      order: 1,
      load: 0.65,
      reps: 5,
    },
    {
      id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1Y",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-4",
      exerciseId: "barbell-squat",
      order: 2,
      load: 0.75,
      reps: 5,
    },
    {
      id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6Z",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-4",
      exerciseId: "barbell-squat",
      order: 3,
      load: 0.85,
      reps: 5,
    },
    {
      id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5A",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-5",
      exerciseId: "barbell-overhead-press",
      order: 1,
      load: 0.7,
      reps: 3,
    },
    {
      id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3B",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-5",
      exerciseId: "barbell-overhead-press",
      order: 2,
      load: 0.8,
      reps: 3,
    },
    {
      id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2C",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-5",
      exerciseId: "barbell-overhead-press",
      order: 3,
      load: 0.9,
      reps: 3,
    },
    {
      id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1D",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-6",
      exerciseId: "barbell-deadlift",
      order: 1,
      load: 0.7,
      reps: 3,
    },
    {
      id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6E",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-6",
      exerciseId: "barbell-deadlift",
      order: 2,
      load: 0.8,
      reps: 3,
    },
    {
      id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5F",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-6",
      exerciseId: "barbell-deadlift",
      order: 3,
      load: 0.9,
      reps: 3,
    },
    {
      id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3G",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-7",
      exerciseId: "barbell-bench-press",
      order: 1,
      load: 0.7,
      reps: 3,
    },
    {
      id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2H",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-7",
      exerciseId: "barbell-bench-press",
      order: 2,
      load: 0.8,
      reps: 3,
    },
    {
      id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1I",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-7",
      exerciseId: "barbell-bench-press",
      order: 3,
      load: 0.9,
      reps: 3,
    },
    {
      id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6J",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-8",
      exerciseId: "barbell-squat",
      order: 1,
      load: 0.7,
      reps: 3,
    },
    {
      id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5K",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-8",
      exerciseId: "barbell-squat",
      order: 2,
      load: 0.8,
      reps: 3,
    },
    {
      id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3L",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-8",
      exerciseId: "barbell-squat",
      order: 3,
      load: 0.9,
      reps: 3,
    },
    {
      id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2M",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-9",
      exerciseId: "barbell-overhead-press",
      order: 1,
      load: 0.75,
      reps: 5,
    },
    {
      id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1N",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-9",
      exerciseId: "barbell-overhead-press",
      order: 2,
      load: 0.85,
      reps: 3,
    },
    {
      id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6O",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-9",
      exerciseId: "barbell-overhead-press",
      order: 3,
      load: 0.95,
      reps: 1,
    },
    {
      id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5P",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-10",
      exerciseId: "barbell-deadlift",
      order: 1,
      load: 0.75,
      reps: 5,
    },
    {
      id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3Q",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-10",
      exerciseId: "barbell-deadlift",
      order: 2,
      load: 0.85,
      reps: 3,
    },
    {
      id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2R",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-10",
      exerciseId: "barbell-deadlift",
      order: 3,
      load: 0.95,
      reps: 1,
      progression: {
        increment: {
          value: 10,
          kind: "weight",
          type: "absolute",
          frequency: 1,
        },
        decrement: {
          value: 0.1,
          kind: "weight",
          type: "percentage",
          frequency: 3,
        },
      },
    },
    {
      id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1S",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-11",
      exerciseId: "barbell-bench-press",
      order: 1,
      load: 0.75,
      reps: 5,
    },
    {
      id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6T",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-11",
      exerciseId: "barbell-bench-press",
      order: 2,
      load: 0.85,
      reps: 3,
    },
    {
      id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5U",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-11",
      exerciseId: "barbell-bench-press",
      order: 3,
      load: 0.95,
      reps: 1,
      progression: {
        increment: {
          value: 10,
          kind: "weight",
          type: "absolute",
          frequency: 1,
        },
        decrement: {
          value: 0.1,
          kind: "weight",
          type: "percentage",
          frequency: 3,
        },
      },
    },
    {
      id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3V",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-12",
      exerciseId: "barbell-squat",
      order: 1,
      load: 0.75,
      reps: 5,
    },
    {
      id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2W",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-12",
      exerciseId: "barbell-squat",
      order: 2,
      load: 0.85,
      reps: 3,
    },
    {
      id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1X",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-12",
      exerciseId: "barbell-squat",
      order: 3,
      load: 0.95,
      reps: 1,
      progression: {
        increment: {
          value: 10,
          kind: "weight",
          type: "absolute",
          frequency: 1,
        },
        decrement: {
          value: 0.1,
          kind: "weight",
          type: "percentage",
          frequency: 3,
        },
      },
    },
    {
      id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6Y",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-13",
      exerciseId: "barbell-overhead-press",
      order: 1,
      load: 0.4,
      reps: 5,
    },
    {
      id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5Z",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-13",
      exerciseId: "barbell-overhead-press",
      order: 2,
      load: 0.5,
      reps: 5,
    },
    {
      id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3a",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-13",
      exerciseId: "barbell-overhead-press",
      order: 3,
      load: 0.6,
      reps: 5,
    },
    {
      id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2b",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-14",
      exerciseId: "barbell-deadlift",
      order: 1,
      load: 0.4,
      reps: 5,
    },
    {
      id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1c",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-14",
      exerciseId: "barbell-deadlift",
      order: 2,
      load: 0.5,
      reps: 5,
    },
    {
      id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6d",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-14",
      exerciseId: "barbell-deadlift",
      order: 3,
      load: 0.6,
      reps: 5,
    },
    {
      id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5e",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-15",
      exerciseId: "barbell-bench-press",
      order: 1,
      load: 0.4,
      reps: 5,
    },
    {
      id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3f",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-15",
      exerciseId: "barbell-bench-press",
      order: 2,
      load: 0.5,
      reps: 5,
    },
    {
      id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2g",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-15",
      exerciseId: "barbell-bench-press",
      order: 3,
      load: 0.6,
      reps: 5,
    },
    {
      id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1h",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-16",
      exerciseId: "barbell-squat",
      order: 1,
      load: 0.4,
      reps: 5,
    },
    {
      id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6i",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-16",
      exerciseId: "barbell-squat",
      order: 2,
      load: 0.5,
      reps: 5,
    },
    {
      id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5j",
      programId: "531-hypertrophy",
      routineId: "531-hypertrophy-16",
      exerciseId: "barbell-squat",
      order: 3,
      load: 0.6,
      reps: 5,
    },
  ];
  await db.templates.bulkInsert(templates);
}
