import type { TemplatesDocType } from "./templates";

// Complete Madcow 5x5 template data for bulk insert
export const madcowTemplatesData: TemplatesDocType[] = [
  {
    id: "ivF7ZkiARfM2M7Keez9a2t",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-squat",
    order: 1,
    load: (100 - 12.5 * 4) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "6qX4vHhkQBpLBS1MBHZLpm",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-squat",
    order: 2,
    load: (100 - 12.5 * 3) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "ithdu5RqaZuEzAbfkBTjNv",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-squat",
    order: 3,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "aATWs7ZJaF9Mdn7JQXR82P",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-squat",
    order: 4,
    load: (100 - 12.5 * 1) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "mxYn7w7cJM6CQZSsqC3CqF",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-squat",
    order: 5,
    load: 1,
    repRange: { min: 5, max: 5 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "tVmFUHxUZ8bqg31iATtdnF",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-bench-press",
    order: 6,
    load: (100 - 12.5 * 4) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "ctRAMxTzUpRjnHF53dhyan",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-bench-press",
    order: 7,
    load: (100 - 12.5 * 3) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "ePs6JuJA6yM2TaUUF3imGi",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-bench-press",
    order: 8,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "npYQG18GDMiE2HAE94VaXP",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-bench-press",
    order: 9,
    load: (100 - 12.5 * 1) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "3eVPe9SdyH1a564VLv8ZCA",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-bench-press",
    order: 10,
    load: 1,
    repRange: { min: 5, max: 5 },
     progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 2.5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "ikRzQZZJ2P8NpXxuS8oFTy",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-row",
    order: 11,
    load: (100 - 12.5 * 4) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "tiA47tvRcqSeDH3cWFYsc3",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-row",
    order: 12,
    load: (100 - 12.5 * 3) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "pc8AkLGCS19V1DdGFu3vSm",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-row",
    order: 13,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "s9cTP7dPWtecJJvarpW7US",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-row",
    order: 14,
    load: (100 - 12.5 * 1) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "ft75Su2gbZEYoKi4jzyTCc",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "barbell-row",
    order: 15,
    load: 1,
    repRange: { min: 5, max: 5 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 2.5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "sj6AGpGBbdZgdNFfScirm3",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "dips",
    order: 16,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "qRGMLt2QfWdQnX7N1Qg7um",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "dips",
    order: 17,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "xgqCuyZt1HRGSGE7pSPTX5",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "dips",
    order: 18,
    load: 1,
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "kEe6TMkc3xu4RnjafEDSW6",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "hanging-knee-raise",
    order: 19,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "1SG1KbPecumNhjUa6VtwAN",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "hanging-knee-raise",
    order: 20,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "hLyKjRjHDFwkmb1aNvr33D",
    programId: "madcow",
    routineId: "madcow-routine-1",
    exerciseId: "hanging-knee-raise",
    order: 21,
    load: 1,
    repRange: { min: 3, max: 10 },
    progressionConfig: {
      type: "reps" as const,
      incrementType: "fixed" as const,
      repsIncrement: 1,
      enableWeightProgression: true,
      weightIncrement: 5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "iRW2LuAjsXeQURtp8ogrSx",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-squat",
    order: 1,
    load: (100 - 12.5 * 4) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "rv9LUo6iRkP1VWWeTokxd9",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-squat",
    order: 2,
    load: (100 - 12.5 * 3) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "22cUxKt7F5G9xSxFLmQqqf",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-squat",
    order: 3,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "ijVwd57YuWUNzHCnLV3mej",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-squat",
    order: 4,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "bfMDfWNux5XL67zMNPtjpB",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-incline-bench-press",
    order: 5,
    load: (100 - 12.5 * 3) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "rUYQqJhAW25JQMKzcKPSRu",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-incline-bench-press",
    order: 6,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "aiK4Y9rknpWpash88jUFuN",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-incline-bench-press",
    order: 7,
    load: (100 - 12.5 * 1) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "1fKxz6Rmrqom7Wt1zBdhP3",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-incline-bench-press",
    order: 8,
    load: 1,
    repRange: { min: 5, max: 5 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 2.5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "mF9RnHz8FfpcADbxFPPWuJ",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-deadlift",
    order: 9,
    load: (100 - 12.5 * 3) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "3pYLTVRtnKATyVoXsyckDR",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-deadlift",
    order: 10,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "94uHihiPKMR28P4aKmyS3t",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-deadlift",
    order: 11,
    load: (100 - 12.5 * 1) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "ccNqFrj5feJsQQHzM2XU4x",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "barbell-deadlift",
    order: 12,
    load: 1,
    repRange: { min: 5, max: 5 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 10,
      weightRoundingIncrement: 5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "uunFS2R8DAKUa41yStjvRy",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "pullups",
    order: 13,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "v4Bu7DfjtQQysNPhxJsnCQ",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "pullups",
    order: 14,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "9cM7aeiwR5yUP9CotfGgUQ",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "pullups",
    order: 15,
    load: 1,
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "r5iCwNYxyTo5PC2kzZ8Hx2",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "planks",
    order: 16,
    load: 1,
    timeRange: { min: 10, max: 60 },
  },
  {
    id: "k7qWy1gZwQU2sRihmCjbsZ",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "planks",
    order: 17,
    load: 1,
    timeRange: { min: 10, max: 60 },
  },
  {
    id: "utjRLE2oXyJnVgbA3hyGd4",
    programId: "madcow",
    routineId: "madcow-routine-2",
    exerciseId: "planks",
    order: 18,
    load: 1,
    timeRange: { min: 10, max: 60 },
    progressionConfig: {
      type: "time" as const,
      timeIncrement: 10,
      timeRoundingIncrement: 10,
      enableWeightProgression: true,
      incrementType: "fixed" as const,
      weightIncrement: 5,
      weightRoundingIncrement: 5,
      deloadStrategy: "time-then-weight" as const,
      deloadType: "fixed" as const,
      deloadAmount: 5,
      failureThreshold: 3,
    },
  },
  {
    id: "fE4uG3xqR7Rm1e9dxWrYqa",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-squat",
    order: 1,
    load: (100 - 12.5 * 4) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "sXZ3Z6AkcjZzAyiAmQEiwS",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-squat",
    order: 2,
    load: (100 - 12.5 * 3) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "aYUGS8Z8ebjrHVEyc2KDRz",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-squat",
    order: 3,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "6ysaYxyHGFsA7khFqmFeog",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-squat",
    order: 4,
    load: (100 - 12.5 * 1) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "dBnztPdAEmNoALBtLEN3Ly",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-squat",
    order: 5,
    load: (100 + 12.5) / 100,
    repRange: { min: 3, max: 3 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 10,
      weightRoundingIncrement: 10,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "mmevFKe6R41RfH9PZEhVLV",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-squat",
    order: 6,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "ntkjx6ghGHuAYKkNfjRWBV",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-bench-press",
    order: 7,
    load: (100 - 12.5 * 4) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "jWLxoJuCYw4X9LkbWA1M7v",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-bench-press",
    order: 8,
    load: (100 - 12.5 * 3) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "mK9BnVZ3FRarggHW3miU7S",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-bench-press",
    order: 9,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "crcSp1F7xzAXnL3qvJyUK4",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-bench-press",
    order: 10,
    load: (100 - 12.5 * 1) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "6pUGx8sDsLW5UcaEsUexJ4",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-bench-press",
    order: 11,
    load: (100 + 12.5) / 100,
    repRange: { min: 3, max: 3 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 2.5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "kFCSdUKNMSXq9cNHuZPsmJ",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-bench-press",
    order: 12,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "qz6YhY37ie2Jipuf8se9ii",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-row",
    order: 13,
    load: (100 - 12.5 * 4) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "232pS17GjAUXt2esQD4mPr",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-row",
    order: 14,
    load: (100 - 12.5 * 3) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "iZYMXiqxhwUAWWZn7TRwME",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-row",
    order: 15,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "6HVcTcFcNYVexAwsoUTuGj",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-row",
    order: 16,
    load: (100 - 12.5 * 1) / 100,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "rFGS5Dr2Me7y1gyUf8oJDx",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-row",
    order: 17,
    load: (100 + 12.5) / 100,
    repRange: { min: 3, max: 3 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 2.5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "6MqtBwRRUo8kupYXzMYULV",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-row",
    order: 18,
    load: (100 - 12.5 * 2) / 100,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "5VPK9wT6ooK173mgTY3w3z",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-curl",
    order: 19,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "4cNQ5gyx39ePYS9pJaQBY9",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-curl",
    order: 20,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "oCC4X3bjztA2ZWqZg2pVPa",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "barbell-curl",
    order: 21,
    load: 1,
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 2.5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "jYKbLb47HkzRHUK2tzsBfk",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "ezbar-skullcrusher",
    order: 22,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "99stSC2YfcHZSUsiQ6akqX",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "ezbar-skullcrusher",
    order: 23,
    load: 1,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "mgcTxF7P6RS2odiGdkSDY7",
    programId: "madcow",
    routineId: "madcow-routine-3",
    exerciseId: "ezbar-skullcrusher",
    order: 24,
    load: 1,
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 2.5,
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
];
