import type { MyDatabase } from "./db";
import type { TemplatesDocType } from "./templates";

export const five31HypertrophyTemplatesData: TemplatesDocType[] = [
  // main sets
  {
    id: "hQ8w2e9r4t5y6u7i8o1p0az",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "barbell-overhead-press",
    order: 1,
    load: 0.65,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "mZ2xVb7Lp9Qw3Er1Tg6Yh5N",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "barbell-overhead-press",
    order: 2,
    load: 0.75,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Jk5Lm8Qw2Zx1Vb3Er7Tg4Q",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "barbell-overhead-press",
    order: 3,
    load: 0.85,
    repRange: { min: 5, max: 5 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "a1B2c3D4e5F6g7H8j9K0Lm",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "barbell-overhead-press",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "pQ2rS3tU4vW5xY6zA7bC8dE",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "barbell-overhead-press",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "fG9hJ0kL1mN2oP3qR4sT5uV",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "barbell-overhead-press",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "wX6yZ7aB8cD9eF0gH1iJ2kL",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "barbell-overhead-press",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "M3nO4pQ5rS6tU7vW8xY9zA0",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "barbell-overhead-press",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "bC1dE2fG3hJ4kL5mN6oP7qR",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "pullups",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "S8tU9vW0xY1zA2bC3dE4fG5",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "pullups",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "hJ6kL7mN8oP9qR0sT1uV2wX",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "pullups",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "yZ3aB4cD5eF6gH7iJ8kL9mN",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "pullups",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "O0pQ1rS2tU3vW4xY5zA6bC7",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-1",
    exerciseId: "pullups",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 2
  //

  // main sets
  {
    id: "Er6Tg2Yh9Nq3Wb5Lp8Zx1R",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "barbell-deadlift",
    order: 1,
    load: 0.65,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Lp7Zx1Vb3Er6Tg2Yh9Nq5S",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "barbell-deadlift",
    order: 2,
    load: 0.75,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Yh9Nq3Wb5Lp8Zx1Vb2Er6T",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "barbell-deadlift",
    order: 3,
    load: 0.85,
    repRange: { min: 5, max: 5 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5T",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "barbell-deadlift",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3U",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "barbell-deadlift",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg3V",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "barbell-deadlift",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1W",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "barbell-deadlift",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6X",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "barbell-deadlift",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "dE8fG9hJ0kL1mN2oP3qR4sT",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "hanging-knee-raise",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "U5vW6xY7zA8bC9dE0fG1hJ2",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "hanging-knee-raise",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "kL3mN4oP5qR6sT7uV8wX9yZ",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "hanging-knee-raise",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "aB1cD2eF3gH4iJ5kL6mN7oP",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "hanging-knee-raise",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Q1rS2tU3vW4xY5zA6bC7dE8",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-2",
    exerciseId: "hanging-knee-raise",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 3
  //

  // main sets
  {
    id: "Nq5Wb7Lp9Zx2Vb3Er6Tg1U",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "barbell-bench-press",
    order: 1,
    load: 0.65,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Tg4Nq7Wb2Lp8Zx1Vb3Er6V",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "barbell-bench-press",
    order: 2,
    load: 0.75,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Vb3Er6Tg2Yh9Nq5Wb7Lp8W",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "barbell-bench-press",
    order: 3,
    load: 0.85,
    repRange: { min: 5, max: 5 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5X",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "barbell-bench-press",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3Y",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "barbell-bench-press",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2Z",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "barbell-bench-press",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "barbell-bench-press",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6b",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "barbell-bench-press",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "uV5wX6yZ7aB8cD9eF0gH1iJ",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "dumbbell-row-one-arm",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "kL2mN3oP4qR5sT6uV7wX8yZ",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "dumbbell-row-one-arm",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Y2vT7yL4nW9sK1pJ6zB5mR8u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "dumbbell-row-one-arm",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "M5nW2vQ8yT1sL6pJ9zB4kR7a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "dumbbell-row-one-arm",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "T4yQ9vL2nW7sK1pJ8zB5mR3u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-3",
    exerciseId: "dumbbell-row-one-arm",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 4
  //

  // main sets
  {
    id: "Zx1Vb3Er6Tg2Yh9Nq5Wb7X",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "barbell-squat",
    order: 1,
    load: 0.65,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1Y",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "barbell-squat",
    order: 2,
    load: 0.75,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6Z",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "barbell-squat",
    order: 3,
    load: 0.85,
    repRange: { min: 5, max: 5 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "barbell-squat",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3b",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "barbell-squat",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2c",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "barbell-squat",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1d",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "barbell-squat",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6e",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "barbell-squat",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5f",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "leg-curl",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3g",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "leg-curl",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2h",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "leg-curl",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1i",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "leg-curl",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "W2xY3zA4bC5dE6fG7hJ8kL9",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-4",
    exerciseId: "leg-curl",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 5
  //

  // main sets
  {
    id: "F8kM1nW7vQ2yT5sL9pJ4zB6a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "barbell-overhead-press",
    order: 1,
    load: 0.7,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "Q1vT6yL3nW8sK2pJ9zB5mR4u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "barbell-overhead-press",
    order: 2,
    load: 0.8,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "N7wT2yQ5vL8sK3pJ1zB6mR9a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "barbell-overhead-press",
    order: 3,
    load: 0.9,
    repRange: { min: 3, max: 3 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "B6pJ3lK9yQ2vT8nS5wM1fR4u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "barbell-overhead-press",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "D5kM2nW8vQ1yT6sL9pJ4zB7a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "barbell-overhead-press",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "S3nF8vQ1tL6yB9kJ2zP5mW0r",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "barbell-overhead-press",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "P6jB3lK8yQ2vT9mS4nW0fR5u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "barbell-overhead-press",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "K2lM3nO4pQ5rS6tU7vW8xY9",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "barbell-overhead-press",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "R8vQ2nL5yT7sW3kJ1zF6bX0p",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "pullups",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "C7dE8fG9hJ0kL1mN2oP3qR4",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "pullups",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "mN0oP1qR2sT3uV4wX5yZ6aB",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "pullups",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5K",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "pullups",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Q7rS8tU9vW0xY1zA2bC3dE4",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-5",
    exerciseId: "pullups",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 6
  //

  // main sets
  {
    id: "zA0bC1dE2fG3hJ4kL5mN6oP",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "barbell-deadlift",
    order: 1,
    load: 0.7,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "V9qS4nL1yT8wK2mJ7pB5fR3z",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "barbell-deadlift",
    order: 2,
    load: 0.8,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "L2wT7yQ4vN9sK1pM8jB5fR3x",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "barbell-deadlift",
    order: 3,
    load: 0.9,
    repRange: { min: 3, max: 3 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3c",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "barbell-deadlift",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2d",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "barbell-deadlift",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1e",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "barbell-deadlift",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6f",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "barbell-deadlift",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5g",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "barbell-deadlift",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3h",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "hanging-knee-raise",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2i",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "hanging-knee-raise",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1j",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "hanging-knee-raise",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6k",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "hanging-knee-raise",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5l",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-6",
    exerciseId: "hanging-knee-raise",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 7
  //

  // main sets
  {
    id: "G7xC1zH5pL2qV8sN4wD0kM9a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "barbell-bench-press",
    order: 1,
    load: 0.7,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "U4cM9dS2wE8hV7qA5tN1rZ3x",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "barbell-bench-press",
    order: 2,
    load: 0.8,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "sT5uV6wX7yZ8aB9cD0eF1gH",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "barbell-bench-press",
    order: 3,
    load: 0.9,
    repRange: { min: 3, max: 3 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5m",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "barbell-bench-press",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3n",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "barbell-bench-press",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2o",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "barbell-bench-press",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1p",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "barbell-bench-press",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6q",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "barbell-bench-press",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5r",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "dumbbell-row-one-arm",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3s",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "dumbbell-row-one-arm",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2t",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "dumbbell-row-one-arm",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "dumbbell-row-one-arm",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6v",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-7",
    exerciseId: "dumbbell-row-one-arm",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 8
  //

  // main sets
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6J",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "barbell-squat",
    order: 1,
    load: 0.7,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "fG5hJ6kL7mN8oP9qR0sT1uV",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "barbell-squat",
    order: 2,
    load: 0.8,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3L",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "barbell-squat",
    order: 3,
    load: 0.9,
    repRange: { min: 3, max: 3 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5w",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "barbell-squat",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2x",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "barbell-squat",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "C3kM8nW1vQ6yT9sL2pJ5zB7a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "barbell-squat",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "E9wT4yQ1vL7sK2pJ8zB5mR6u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "barbell-squat",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "H6nW3vQ9yT2sL5pJ1zB8kR4a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "barbell-squat",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5y",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "leg-curl",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3z",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "leg-curl",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2A",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "leg-curl",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1B",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "leg-curl",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6C",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-8",
    exerciseId: "leg-curl",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 9
  //

  // main sets
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2M",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "barbell-overhead-press",
    order: 1,
    load: 0.75,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1N",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "barbell-overhead-press",
    order: 2,
    load: 0.85,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6O",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "barbell-overhead-press",
    order: 3,
    load: 0.95,
    repRange: { min: 1, max: 1 },
    amrep: true,
    progressionConfig: {
      type: "linear",
      progressionSets: [3], // Only this set counts for progression
      incrementType: "fixed",
      weightIncrement: 10, // +10 lbs for overhead press
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage",
      deloadType: "percentage", 
      deloadAmount: 10, // -10% on deload
      failureThreshold: 3,
    },
  },
  // hypertrophy sets
  {
    id: "Z1vT8yL5nW2sK9pJ4zB7mR3u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "barbell-overhead-press",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "X7kM2nW5vQ8yT1sL9pJ3zB6a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "barbell-overhead-press",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Q8wR2eT5yU7iO1p0AzX4cV6b",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "barbell-overhead-press",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "M2nP4qS6tV8xZ0aC3dF5hJ7l",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "barbell-overhead-press",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "W9yB2vN5sK8pJ1zR4mT7uQ0x",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "barbell-overhead-press",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "L3kM6oP9qS2tV5xY8zB1cD4e",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "pullups",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "S5uV8wX1yZ4aB7cD0eF3hJ6k",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "pullups",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "J7mN0oP3qR6sT9uV2wX5yZ8a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "pullups",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "C1dE4fG7hJ0kL3mN6oP9qR2s",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "pullups",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "T8uV1wX4yZ7aB0cD3eF6hJ9k",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-9",
    exerciseId: "pullups",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 10
  //

  // main sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5P",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "barbell-deadlift",
    order: 1,
    load: 0.75,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3Q",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "barbell-deadlift",
    order: 2,
    load: 0.85,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2R",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "barbell-deadlift",
    order: 3,
    load: 0.95,
    repRange: { min: 1, max: 1 },
    amrep: true,
    progressionConfig: {
      type: "linear",
      progressionSets: [3], // Only this set counts for progression
      incrementType: "fixed",
      weightIncrement: 10, // +10 lbs for deadlift
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage",
      deloadType: "percentage", 
      deloadAmount: 10, // -10% on deload
      failureThreshold: 3,
    },
  },
  // hypertrophy sets
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1T",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "barbell-deadlift",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6U",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "barbell-deadlift",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5V",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "barbell-deadlift",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3W",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "barbell-deadlift",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "P2qR5sT8uV1wX4yZ7aB0cD3e",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "barbell-deadlift",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2S",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "hanging-knee-raise",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "F6hJ9kL2mN5oP8qR1sT4uV7w",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "hanging-knee-raise",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "R4sT7uV0wX3yZ6aB9cD2eF5h",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "hanging-knee-raise",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "G8jK1mN4pQ7sT0vW3yZ6bC9d",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "hanging-knee-raise",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3X",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-10",
    exerciseId: "hanging-knee-raise",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 11
  //

  // main sets
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1S",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "barbell-bench-press",
    order: 1,
    load: 0.75,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6T",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "barbell-bench-press",
    order: 2,
    load: 0.85,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5U",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "barbell-bench-press",
    order: 3,
    load: 0.95,
    repRange: { min: 1, max: 1 },
    amrep: true,
    progressionConfig: {
      type: "linear",
      progressionSets: [3], // Only this set counts for progression
      incrementType: "fixed",
      weightIncrement: 5, // +5 lbs for bench press
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage",
      deloadType: "percentage", 
      deloadAmount: 10, // -10% on deload
      failureThreshold: 3,
    },
  },
  // hypertrophy sets
  {
    id: "E2fH5iJ8lM1oP4rS7uV0xY3z",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "barbell-bench-press",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "B6cD9fG2hJ5kL8mN1pQ4sT7v",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "barbell-bench-press",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "W0xY3zB6cD9eF2hJ5kL8mN1p",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "barbell-bench-press",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Q4sT7vW0xY3zB6cD9eF2hJ5k",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "barbell-bench-press",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5c",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "barbell-bench-press",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "L8mN1pQ4sT7vW0xY3zB6cD9e",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "dumbbell-row-one-arm",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "F2hJ5kL8mN1pQ4sT7vW0xY3z",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "dumbbell-row-one-arm",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "B6cD9eF2hJ5kL8mN1pQ4sT7v",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "dumbbell-row-one-arm",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "V7nQ3xL8yT2sW5kJ0zF9bM4p",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "dumbbell-row-one-arm",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5D",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-11",
    exerciseId: "dumbbell-row-one-arm",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 12
  //

  // main sets
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3V",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "barbell-squat",
    order: 1,
    load: 0.75,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2W",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "barbell-squat",
    order: 2,
    load: 0.85,
    repRange: { min: 3, max: 3 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1X",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "barbell-squat",
    order: 3,
    load: 0.95,
    repRange: { min: 1, max: 1 },
    amrep: true,
    progressionConfig: {
      type: "linear",
      progressionSets: [3], // Only this set counts for progression
      incrementType: "fixed",
      weightIncrement: 10, // +10 lbs for squat
      weightRoundingIncrement: 2.5,
      deloadStrategy: "percentage",
      deloadType: "percentage", 
      deloadAmount: 10, // -10% on deload
      failureThreshold: 3,
    },
  },
  // hypertrophy sets
  {
    id: "A5cD7eF1gH3iJ6kL2mN8oP0q",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "barbell-squat",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "R2sT4uV6wX8yZ1aB3cD5eF7h",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "barbell-squat",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "K9lM0nO2pQ4rS7tU1vW3xY5z",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "barbell-squat",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "J8kL4mN6oP9qR1sT3uV5wX7y",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "barbell-squat",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Z6aB2cD8eF0gH5iJ7kL1mN3o",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "barbell-squat",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "P4qR6sT8uV0wX2yZ5aB7cD9e",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "leg-curl",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "F3hJ5kL7mN9pQ1rS8tU0vW2x",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "leg-curl",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Y4zA6bC8dE1fG3hJ9kL2mN5o",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "leg-curl",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Q7rS1tU3vW5xY9zA0bC2dE4f",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "leg-curl",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "G6hJ8kL0mN2pQ5rS7tU9vW1x",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-12",
    exerciseId: "leg-curl",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 13
  //

  // main sets
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6Y",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "barbell-overhead-press",
    order: 1,
    load: 0.4,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5Z",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "barbell-overhead-press",
    order: 2,
    load: 0.5,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3a",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "barbell-overhead-press",
    order: 3,
    load: 0.6,
    repRange: { min: 5, max: 5 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "X3yZ5aB7cD0eF2hJ4kL6mN8o",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "barbell-overhead-press",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "P9qR1sT3uV5wX7yZ0aB2cD4e",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "barbell-overhead-press",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "F6hJ8kL1mN3oP5qR7sT9uV0w",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "barbell-overhead-press",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "X2yZ4aB6cD8eF0gH3iJ5kL7m",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "barbell-overhead-press",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "N9pQ1rS3tU5vW7xY0zA2bC4d",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "barbell-overhead-press",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "E6fG8hJ0kL2mN4oP6qR8sT1u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "pullups",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "V3wX5yZ7aB9cD1eF3hJ6kL8m",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "pullups",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "N0pQ2rS4tU6vW8xY1zA3bC5d",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "pullups",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "E7fG9hJ2kL4mN6oP8qR0sT3u",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "pullups",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Q5nR8vL2yT6sW9kJ3zF1bM7pX",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-13",
    exerciseId: "pullups",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 14
  //

  // main sets
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2b",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "barbell-deadlift",
    order: 1,
    load: 0.4,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1c",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "barbell-deadlift",
    order: 2,
    load: 0.5,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6d",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "barbell-deadlift",
    order: 3,
    load: 0.6,
    repRange: { min: 5, max: 5 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "M4cD7eF2hJ9kL5mN0pQ3sT8vW",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "barbell-deadlift",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "S2uV5wX8yZ1aB4cD6eF9hJ0kL",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "barbell-deadlift",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "K1lM4nO7pQ2rS5tU8vW0xY3zB",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "barbell-deadlift",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "J3kL6mN9oP2qR5sT8uV1wX4yZ",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "barbell-deadlift",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Z8aB1cD4eF7gH0iJ3kL6mN9oP",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "barbell-deadlift",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "P5qR8sT2uV0wX3yZ1aB6cD9eF",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "hanging-knee-raise",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "F3hJ6kL8mN1pQ4sT7vW0xY2zB",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "hanging-knee-raise",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Y4zA7bC9dE1fG3hJ5kL2mN6oP",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "hanging-knee-raise",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Q6rS1tU4vW5xY8zA0bC2dE3fG",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "hanging-knee-raise",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "G7hJ9kL2mN4pQ5rS8tU1vW3xY",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-14",
    exerciseId: "hanging-knee-raise",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 15
  //

  // main sets
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5e",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "barbell-bench-press",
    order: 1,
    load: 0.4,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3f",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "barbell-bench-press",
    order: 2,
    load: 0.5,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2g",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "barbell-bench-press",
    order: 3,
    load: 0.6,
    repRange: { min: 5, max: 5 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "P7qR0sT3uV6wX9yZ2aB5cD8eF",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "barbell-bench-press",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "F9hJ2kL5mN8pQ1rS4tU7vW0xY",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "barbell-bench-press",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "X6yZ9aB2cD5eF8hJ1kL4mN7oP",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "barbell-bench-press",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "R3sT6uV9wX2yZ5aB8cD1eF4hJ",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "barbell-bench-press",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "G0kL3mN6oP9qR2sT5uV8wX1yZ",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "barbell-bench-press",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6h",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "dumbbell-row-one-arm",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5i",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "dumbbell-row-one-arm",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Tg2Yh9Nq5Wb7Lp8Zx1Vb3j",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "dumbbell-row-one-arm",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Nq5Wb7Lp8Zx1Vb3Er6Tg2k",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "dumbbell-row-one-arm",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1l",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-15",
    exerciseId: "dumbbell-row-one-arm",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },

  //
  // Day 16
  //

  // main sets
  {
    id: "Er6Tg2Yh9Nq5Wb7Lp8Zx1h",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "barbell-squat",
    order: 1,
    load: 0.4,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Yh9Nq5Wb7Lp8Zx1Vb3Er6i",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "barbell-squat",
    order: 2,
    load: 0.5,
    repRange: { min: 5, max: 5 },
  },
  {
    id: "Lp8Zx1Vb3Er6Tg2Yh9Nq5j",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "barbell-squat",
    order: 3,
    load: 0.6,
    repRange: { min: 5, max: 5 },
    amrep: true,
  },
  // hypertrophy sets
  {
    id: "E5fG8hJ1kL4mN7oP0qR3sT6uV",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "barbell-squat",
    order: 4,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "B2cD5eF8hJ1kL4mN7oP0qR3sT",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "barbell-squat",
    order: 5,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "N1pQ4sT7vW0xY3zB6cD9eF2hJ",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "barbell-squat",
    order: 6,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "W7xY0zB3cD6eF9hJ2kL5mN8pQ",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "barbell-squat",
    order: 7,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "V4wX7yZ0aB3cD6eF9hJ2kL5mN",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "barbell-squat",
    order: 8,
    load: 0.5,
    repRange: { min: 10, max: 10 },
  },
  // additional assistance sets
  {
    id: "P8qR1sT4uV5wX7yZ0aB2cD3eF",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "leg-curl",
    order: 9,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "F6hJ9kL2mN4pQ5rS8tU1vW3xY",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "leg-curl",
    order: 10,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "U8vW1xY4zB7cD0eF3hJ6kL9mN",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "leg-curl",
    order: 11,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "C5dE8fG1hJ4kL7mN0pQ3sT6uV",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "leg-curl",
    order: 12,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
  {
    id: "T2uV5wX8yZ1aB4cD7eF0hJ3kL",
    programId: "531-hypertrophy",
    routineId: "531-hypertrophy-16",
    exerciseId: "leg-curl",
    order: 13,
    load: 1,
    repRange: { min: 10, max: 10 },
  },
];

export async function init531HypertrophyTemplates(db: MyDatabase) {
  await db.templates.bulkInsert(five31HypertrophyTemplatesData);
}
