import type { MyDatabase } from "./db";
import type { TemplatesDocType } from "./templates";

export async function init531TridentTemplates(db: MyDatabase) {
  const templates: Array<TemplatesDocType> = [
    // main sets
    {
      id: "5xTZDiyW9P2RqE77sSTgXd",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "barbell-overhead-press",
      order: 1,
      load: 0.65,
      reps: 5,
    },
    {
      id: "qRvgjVfrczqPMPZCsT3fG9",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "barbell-overhead-press",
      order: 2,
      load: 0.75,
      reps: 5,
    },
    {
      id: "pMWkw3v4WBQa3rGdwSvx6W",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "barbell-overhead-press",
      order: 3,
      load: 0.85,
      reps: 5,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "sNETpWkeDadF3nBLdqqspn",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "dips",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "1mpGbKyLCLVFHKov2zgDqn",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "dips",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "nYZrta5TxxCMf1aQRem2w1",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "dips",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "3MjNmex5ikZbidEZ3p8Frb",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "dips",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "mc5Vce9UeEPCvLrJHULDCd",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "dips",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "8zq8wquKWpzhXN3K5FUmsJ",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "pullups",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "rimvNs5DuLS1JFkxaxkvzb",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "pullups",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "gpW1FUPDS1v3t6tw3NenRN",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "pullups",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "9jod6ws7m1sWvzGQKF5GTB",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "pullups",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "xeaczChH6AY6a4aQUJSuRK",
      programId: "531-trident",
      routineId: "531-trident-1",
      exerciseId: "pullups",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 2
    //

    // main sets
    {
      id: "sje9w8tbAy7381x6y9qtic",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "barbell-deadlift",
      order: 1,
      load: 0.65,
      reps: 5,
    },
    {
      id: "dUEuDS457YsyLfamJ44zWx",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "barbell-deadlift",
      order: 2,
      load: 0.75,
      reps: 5,
    },
    {
      id: "fKoMseosk9D65LoLC8kCvy",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "barbell-deadlift",
      order: 3,
      load: 0.85,
      reps: 5,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "773DXnLLQf11Yh88jR5jj1",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "barbell-good-morning",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "x8BxEfxqy3HiiJHZ5QHErP",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "barbell-good-morning",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "29uDL8Dy2xCBqdtZbQkN7Q",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "barbell-good-morning",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "ezTQvLBtCoXSAzAk8qPUSV",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "barbell-good-morning",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "qES8NoxzqEufzSjQnpmniD",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "barbell-good-morning",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "ttSD8owCk8S668CTtfdhBo",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "hanging-knee-raise",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "uXpToBHmmMgtpQXm4xa8vN",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "hanging-knee-raise",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "r644TLTN1MigEGPCBhF3kM",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "hanging-knee-raise",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "8atQ8Ccpzeqk9E4FFpQJhR",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "hanging-knee-raise",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "mo9Nna6WbJ7FYwo32p7NsD",
      programId: "531-trident",
      routineId: "531-trident-2",
      exerciseId: "hanging-knee-raise",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 3
    //

    // main sets
    {
      id: "aLTDcDHWjwWCSoVtSuXZED",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "barbell-bench-press",
      order: 1,
      load: 0.65,
      reps: 5,
    },
    {
      id: "tknwhbebya2xavSGR53dg9",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "barbell-bench-press",
      order: 2,
      load: 0.75,
      reps: 5,
    },
    {
      id: "1wMPKDu5LZBP9ozhWrNaDc",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "barbell-bench-press",
      order: 3,
      load: 0.85,
      reps: 5,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "eZSRxV3FJYuEw69G7SNwZA",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-bench-press",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "or3t1ESXoVK91U3cZKDSqv",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-bench-press",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "fGqKHYrb8s5qYtX5ziNtDc",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-bench-press",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "323uPHNzsSGFxAfiLasbmh",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-bench-press",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "eqjHbD851yLsnwQyYpCVEi",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-bench-press",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "h2k4ND6U53Ejadjue7oYBN",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-row-one-arm",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "9N91BsdBSfC7j9JVWPB4h7",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-row-one-arm",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "qySGmCoZTLsaTbnewZYZtx",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-row-one-arm",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "fNiKkFuMaMv3fcc8U9Ft6T",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-row-one-arm",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "gSKULRVr1yWpZ2uz85Wrok",
      programId: "531-trident",
      routineId: "531-trident-3",
      exerciseId: "dumbbell-row-one-arm",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 4
    //

    // main sets
    {
      id: "hNcPQ3eMkYgg1rTLVBdT5m",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "barbell-squat",
      order: 1,
      load: 0.65,
      reps: 5,
    },
    {
      id: "hGfoiqfSzfff7gJZYQi5cE",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "barbell-squat",
      order: 2,
      load: 0.75,
      reps: 5,
    },
    {
      id: "rwHsYzZ6iGWiJ7KWF4gLZ7",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "barbell-squat",
      order: 3,
      load: 0.85,
      reps: 5,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "ieUhYGNnTk9Y1Tt3rpcr3U",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-press",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "fU3LLoPM92dTaE4cKQaZwg",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-press",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "4KneWZiLNCFKNsVkNt8y7L",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-press",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "snFcF6A7PJbqL1qHjkEEGx",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-press",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "aHLr6mCmqRxsM29aWqzchH",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-press",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "iX5bX2jCxbqPHb284houEV",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-curl",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "hygLgnnWmp6EgTnMJkNctw",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-curl",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "hefgFefsCDy9ecEPWoKJNJ",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-curl",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "jYpTD1jbuH2eKb2eMijP9e",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-curl",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "mQo6dhsjW9ajvPMKx79vsv",
      programId: "531-trident",
      routineId: "531-trident-4",
      exerciseId: "leg-curl",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 5
    //

    // main sets
    {
      id: "gVbk4f3m7e1pbWxrxnKPaS",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "barbell-overhead-press",
      order: 1,
      load: 0.7,
      reps: 3,
    },
    {
      id: "qxqGx52bnDwpEcV8mJqEqG",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "barbell-overhead-press",
      order: 2,
      load: 0.8,
      reps: 3,
    },
    {
      id: "thj6q5jdT7QV1fyr1PDvFk",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "barbell-overhead-press",
      order: 3,
      load: 0.9,
      reps: 3,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "gjYwCrSzSqv2YVKnsf4z88",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "dips",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "b8sJRnCjKYoBWpHneKycQr",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "dips",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "skuRa7TvPqXcsKzs3fBPZg",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "dips",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "eeMmYPesQwRqcbxB9Q7Q7d",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "dips",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "c49qajgv4g4ws68k4KXLEA",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "dips",
      order: 7,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "w94GifFkAU9h1gKdMCCbNu",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "pullups",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "7Jwte215aagzupxo4ygbjo",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "pullups",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "osFzbCwPHwdjVWRVWRTXEY",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "pullups",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "cKEdL4NiX9gfLZtc74ZXyq",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "pullups",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "5KNxi9q2fgJQQ64c8NGUtZ",
      programId: "531-trident",
      routineId: "531-trident-5",
      exerciseId: "pullups",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 6
    //

    // main sets
    {
      id: "1mzuxEDJvhwpooaqaAiVFv",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "barbell-deadlift",
      order: 1,
      load: 0.7,
      reps: 3,
    },
    {
      id: "hoxb1qvG2CxSxNLtvzUyae",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "barbell-deadlift",
      order: 2,
      load: 0.8,
      reps: 3,
    },
    {
      id: "9KnLG6w2mnch2jsyEe8yvF",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "barbell-deadlift",
      order: 3,
      load: 0.9,
      reps: 3,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "aNwkuVw2eR64ofdyzDqudH",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "barbell-good-morning",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "ckrbBjHnesKGyYaMwBe5oX",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "barbell-good-morning",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "sQjbjfgGPWdTV1Faqxufub",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "barbell-good-morning",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "kY5a7bCpGGLg84BfaVUV1Q",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "barbell-good-morning",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "uuJemkW5koAPyoQVMthb9a",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "barbell-good-morning",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "twCEQK8Rs4cFGVBJn85m4u",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "hanging-knee-raise",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "ifvbXCBg6MBxQ4pguSJAU2",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "hanging-knee-raise",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "kWWHWDux7FHQTFfJETsp2H",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "hanging-knee-raise",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "tUiaovMN4mnQFFmb4BHFhy",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "hanging-knee-raise",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "nkbjCGvuWPPsHykehH1NZF",
      programId: "531-trident",
      routineId: "531-trident-6",
      exerciseId: "hanging-knee-raise",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 7
    //

    // main sets
    {
      id: "95KkU7wPo7chqLBxoXGc6E",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "barbell-bench-press",
      order: 1,
      load: 0.7,
      reps: 3,
    },
    {
      id: "2Aq5WTR6M8WakpNoeKn1Cu",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "barbell-bench-press",
      order: 2,
      load: 0.8,
      reps: 3,
    },
    {
      id: "3ffpDRfMBzZPkyYW6cdd4a",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "barbell-bench-press",
      order: 3,
      load: 0.9,
      reps: 3,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "1XFaaFduodQ1H5KTXMaJUn",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-bench-press",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "tnJCU7B1XsZ5v7d4PY941a",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-bench-press",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "882DgN9Neck12KdGWZ9ngU",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-bench-press",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "edMxCWUWhZctFKdc4So67T",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-bench-press",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "mjxpcVGV6ZogbthbAj9SWX",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-bench-press",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "88eQ7RKDcjF8znogdb9uvW",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-row-one-arm",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "nVLkiSKKrFJBSGt86yJM96",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-row-one-arm",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "guoNzfgtNut4pox2es7rzo",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-row-one-arm",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "7FBMeCgstMBesSdJmcgu2F",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-row-one-arm",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "pxiaAbkKW5Twzy9BZwnK5H",
      programId: "531-trident",
      routineId: "531-trident-7",
      exerciseId: "dumbbell-row-one-arm",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 8
    //

    // main sets
    {
      id: "5nURg6d3GSFpURjvimsMNT",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "barbell-squat",
      order: 1,
      load: 0.7,
      reps: 3,
    },
    {
      id: "57GpQcwz15N1HVwfuMzrMH",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "barbell-squat",
      order: 2,
      load: 0.8,
      reps: 3,
    },
    {
      id: "5paCjPqE2tbDzky52eipeT",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "barbell-squat",
      order: 3,
      load: 0.9,
      reps: 3,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "6dprqnEC2RJgfDUSqhfxUQ",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-press",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "mWvCrAQBCBMGAveXmDwWrv",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-press",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "hFXEkAiHND7JYopYG5VnF5",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-press",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "i815TsE8fyx1gUgCNJ6Jfg",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-press",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "aTHTEHbj1zGZhigkuDcHqt",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-press",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "4R6XiQbcNeMRyVX4SRPACU",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-curl",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "h53RXj4wc5YNtirKPR315G",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-curl",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "8sZHSBmXjQbh5A8ewLn3uv",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-curl",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "ttHQxnNL2w9MzSyoDSEv5Z",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-curl",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "dauMSWwR8ZdWCny465VKks",
      programId: "531-trident",
      routineId: "531-trident-8",
      exerciseId: "leg-curl",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 9
    //

    // main sets
    {
      id: "mim5v9gd7cpGkGxZozChSA",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "barbell-overhead-press",
      order: 1,
      load: 0.75,
      reps: 5,
    },
    {
      id: "8XJZSUmTtmNxNFbJD3FP4R",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "barbell-overhead-press",
      order: 2,
      load: 0.85,
      reps: 3,
    },
    {
      id: "9qku26Dxvkb9su8Aq5pBkn",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "barbell-overhead-press",
      order: 3,
      load: 0.95,
      reps: 1,
      amrep: true,
      progression: {
        increment: {
          value: 10,
          kind: "weight",
          type: "absolute",
          frequency: 1,
        },
        decrement: {
          value: 0.1,
          kind: "weight",
          type: "percentage",
          frequency: 3,
        },
      },
    },
    // additional assistance sets 1
    {
      id: "s3f7Ns6abda17WaUU6xS2f",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "dips",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "b3uTGWWneHv3PZFiD2Ap72",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "dips",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "8UKmNT67uDnUL9Wxa3hp1E",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "dips",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "e4p9GPPUowAcNhKAE2GtYE",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "dips",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "jG8zVAfyHpKh3JNrdgt82J",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "dips",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "4oFWETucF3dPBNcVotnwsd",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "pullups",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "qAEQdaeLJZLN6QbTAnd92e",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "pullups",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "uJUcZc7r7LPenX3EqtzTGq",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "pullups",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "8iQLUEFgSTLzZraFLEtST5",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "pullups",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "q1exBZ35MFvUxhWbBaJtY9",
      programId: "531-trident",
      routineId: "531-trident-9",
      exerciseId: "pullups",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 10
    //

    // main sets
    {
      id: "r8cBwbVCU7woaXDFBwLgbz",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "barbell-deadlift",
      order: 1,
      load: 0.75,
      reps: 5,
    },
    {
      id: "mtdbcnmZx1qXjvn1L5KQ8X",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "barbell-deadlift",
      order: 2,
      load: 0.85,
      reps: 3,
    },
    {
      id: "7YwExtZJp6rpM6igjuHgPW",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "barbell-deadlift",
      order: 3,
      load: 0.95,
      reps: 1,
      amrep: true,
      progression: {
        increment: {
          value: 10,
          kind: "weight",
          type: "absolute",
          frequency: 1,
        },
        decrement: {
          value: 0.1,
          kind: "weight",
          type: "percentage",
          frequency: 3,
        },
      },
    },
    // additional assistance sets 1
    {
      id: "5U5EA3keeQKCxZGX1yE7Px",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "barbell-good-morning",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "hwden6hiHPH38T51LHG6ML",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "barbell-good-morning",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "xn3sVC8oX6kho6VQ96Cd2J",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "barbell-good-morning",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "davjMu7fAyzZ1xnyacYD6c",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "barbell-good-morning",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "bEZgtsRShRwrMLa1e9DTR2",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "barbell-good-morning",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "nGPvstSKywmDngT5696FaG",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "hanging-knee-raise",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "84kEAhHiBfxCPbWpu4Frjb",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "hanging-knee-raise",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "agk8ZxDnDeDHdd96wTr1QZ",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "hanging-knee-raise",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "rVb1thf3Hu8Z7cVpPRfVzb",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "hanging-knee-raise",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "t6K6W3bXBmc7TCGWh8B9rT",
      programId: "531-trident",
      routineId: "531-trident-10",
      exerciseId: "hanging-knee-raise",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 11
    //

    // main sets
    {
      id: "mbAhAfzLAyRWPve9QvusxL",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "barbell-bench-press",
      order: 1,
      load: 0.75,
      reps: 5,
    },
    {
      id: "vmTRWD7eHR4f316Seiqcbb",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "barbell-bench-press",
      order: 2,
      load: 0.85,
      reps: 3,
    },
    {
      id: "2ZWdDX5Aqq5CSFz6cc8tkS",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "barbell-bench-press",
      order: 3,
      load: 0.95,
      reps: 1,
      amrep: true,
      progression: {
        increment: {
          value: 10,
          kind: "weight",
          type: "absolute",
          frequency: 1,
        },
        decrement: {
          value: 0.1,
          kind: "weight",
          type: "percentage",
          frequency: 3,
        },
      },
    },
    // additional assistance sets 1
    {
      id: "15YbuDhfzY3yXxvEmS3abb",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-bench-press",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "5bQtxwFMvXDrpVYPtuWFPs",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-bench-press",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "gDhX21TGRm7V4HWmCFbkwH",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-bench-press",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "v7rMgkdfEC4QdHixPfa4PC",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-bench-press",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "vVQBPVqur6QcnmVRc28SvS",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-bench-press",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "7ADumV7XRaiBwR9mU3VtRk",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-row-one-arm",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "mZyAePGEybhA2WFv1jwve7",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-row-one-arm",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "kBWu5hVhG47PpueeUfdaF7",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-row-one-arm",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "6PeuYknkUXTqP6SFeC512P",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-row-one-arm",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "dUNN8C5Re6qSD5sPwBJQpW",
      programId: "531-trident",
      routineId: "531-trident-11",
      exerciseId: "dumbbell-row-one-arm",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 12
    //

    // main sets
    {
      id: "h7mJCjSbQ3jM4DEFFNomx4",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "barbell-squat",
      order: 1,
      load: 0.75,
      reps: 5,
    },
    {
      id: "iZMRup3dYudyynzskmbmjM",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "barbell-squat",
      order: 2,
      load: 0.85,
      reps: 3,
    },
    {
      id: "1a8DJxLdVCzw7gd3dmCW14",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "barbell-squat",
      order: 3,
      load: 0.95,
      reps: 1,
      amrep: true,
      progression: {
        increment: {
          value: 10,
          kind: "weight",
          type: "absolute",
          frequency: 1,
        },
        decrement: {
          value: 0.1,
          kind: "weight",
          type: "percentage",
          frequency: 3,
        },
      },
    },
    // additional assistance sets 1
    {
      id: "fdfftjR6W7Kj2PXsqZttV3",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-press",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "o14QnN7BMmBPdJWxxK3TUp",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-press",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "5pPB6JqY5pk3deq3m7DQwt",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-press",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "ifWyhknbPWZUvU5rrud3Gv",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-press",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "ixvkuA4an2DeStMMbgwKc5",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-press",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "xcRUY7rMyX3UWVqPJumYoy",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-curl",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "1wxd1W6bosfFCM8T2kRxuQ",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-curl",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "cEYpDQJpFoRik9QHxgs6ob",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-curl",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "cDQhVwg2H6AnaT7SBqQTRv",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-curl",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "9Z6gzUnnKzdQb2zRGKqeaQ",
      programId: "531-trident",
      routineId: "531-trident-12",
      exerciseId: "leg-curl",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 13
    //

    // main sets
    {
      id: "5kRRptgJPLBvGacrMtVbfx",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "barbell-overhead-press",
      order: 1,
      load: 0.4,
      reps: 5,
    },
    {
      id: "eeZYC6zwnyCLYA5BtHnJRS",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "barbell-overhead-press",
      order: 2,
      load: 0.5,
      reps: 5,
    },
    {
      id: "9rKrxGxMtGvtNkS5KV1KoG",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "barbell-overhead-press",
      order: 3,
      load: 0.6,
      reps: 5,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "qbob6GYrm3K8izri2XNdBY",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "dips",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "9369DDghW16Pc9m7K2bFDk",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "dips",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "c7N84npGpeuL2WgBkbeqKB",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "dips",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "3vyDcpUCDKbVygYPfYsP6S",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "dips",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "fXBTb2FkVpp3tbUKQfF3vs",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "dips",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "gZKMSgCxzHHZ9eevqpkuUC",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "pullups",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "g2Ma8CQwiwt2XnTN2briff",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "pullups",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "fEwnF3XWwZwPgmHGAKRjCw",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "pullups",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "bTAVVZwMJyjp1MPgKF9iUS",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "pullups",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "3p4FR2CQJEVtAp7BBbtygz",
      programId: "531-trident",
      routineId: "531-trident-13",
      exerciseId: "pullups",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 14
    //

    // main sets
    {
      id: "aBFvoo2aGSRPj93T5mCQ5K",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "barbell-deadlift",
      order: 1,
      load: 0.4,
      reps: 5,
    },
    {
      id: "4y1bPc9pSmfQidPhEQhpmD",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "barbell-deadlift",
      order: 2,
      load: 0.5,
      reps: 5,
    },
    {
      id: "1CjFpUwesLb3ThKSTTH4Xu",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "barbell-deadlift",
      order: 3,
      load: 0.6,
      reps: 5,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "pT3u4HurBhYkYWvQb5TX4a",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "barbell-good-morning",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "gfwmLhJeFqNxFwTdc8LSjK",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "barbell-good-morning",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "3b6cLwxZqJQ9bb4VaAm9Mx",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "barbell-good-morning",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "uWY61QLJodAhzKdErZsoxM",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "barbell-good-morning",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "cBNowvX8PoGrrNTFpVeq9j",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "barbell-good-morning",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "4WtkfA7Xnn4GbM6WmwSwho",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "hanging-knee-raise",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "xy475GM1zqAFdwwaYmsMQY",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "hanging-knee-raise",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "5TJmiAtKTrMF2UFSUrirKW",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "hanging-knee-raise",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "9ciGd4wgBaPdzqKNuurA5h",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "hanging-knee-raise",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "6PkiEdcy2NdofGwW6n7FeJ",
      programId: "531-trident",
      routineId: "531-trident-14",
      exerciseId: "hanging-knee-raise",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 15
    //

    // main sets
    {
      id: "iP6r29ow2sc12ukwqeGfU6",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "barbell-bench-press",
      order: 1,
      load: 0.4,
      reps: 5,
    },
    {
      id: "it3SnFFeHhkWhwT6cqF17c",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "barbell-bench-press",
      order: 2,
      load: 0.5,
      reps: 5,
    },
    {
      id: "4R4WgjYcKAeYPFyfTuzmev",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "barbell-bench-press",
      order: 3,
      load: 0.6,
      reps: 5,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "u7LcrCR9nxB1j4wswhcxUB",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-bench-press",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "q2CzYeEWC4xFwf9aixi1YG",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-bench-press",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "dDnCfe51yEJPNVyntfkCwa",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-bench-press",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "fwmPzUHE31wek1Ux5K4HVC",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-bench-press",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "8swCe3Ktt2CXBssq7uPW5K",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-bench-press",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "xjEW9XCZXWskGFQEdZXQhg",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-row-one-arm",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "8PaYp7ZaJAQaFS5AJdgjyV",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-row-one-arm",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "weHkULgciDmzdoh6eT5zAe",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-row-one-arm",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "3ZGsc4VkR1Dva3dipHaVZs",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-row-one-arm",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "qsohSbuo2yipZimXZg6doo",
      programId: "531-trident",
      routineId: "531-trident-15",
      exerciseId: "dumbbell-row-one-arm",
      order: 13,
      load: 1,
      reps: 10,
    },

    //
    // Day 16
    //

    // main sets
    {
      id: "rVpM2yV9DMUGyJXefB7NMg",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "barbell-squat",
      order: 1,
      load: 0.4,
      reps: 5,
    },
    {
      id: "9GGwUETHJR7wWh1tFdez7L",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "barbell-squat",
      order: 2,
      load: 0.5,
      reps: 5,
    },
    {
      id: "8mxD3f9q2yWv4iAaBk3w1y",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "barbell-squat",
      order: 3,
      load: 0.6,
      reps: 5,
      amrep: true,
    },
    // additional assistance sets 1
    {
      id: "t2LTWwXRHxph3qmsCgeBKJ",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-press",
      order: 4,
      load: 1,
      reps: 10,
    },
    {
      id: "8yYYTMfXdHjaMB7YFTcdrV",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-press",
      order: 5,
      load: 1,
      reps: 10,
    },
    {
      id: "dNn8VS4ffYD6acwCMMSbow",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-press",
      order: 6,
      load: 1,
      reps: 10,
    },
    {
      id: "3SwZDxsssVXBmuMkLa89n6",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-press",
      order: 7,
      load: 1,
      reps: 10,
    },
    {
      id: "1Thw7YzmQMdXQeeieQQZpU",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-press",
      order: 8,
      load: 1,
      reps: 10,
    },
    // additional assistance sets 2
    {
      id: "cLVmJfu6vnw1eZs1BCUhMF",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-curl",
      order: 9,
      load: 1,
      reps: 10,
    },
    {
      id: "eornDL4wdJZu2CLd4L6VCA",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-curl",
      order: 10,
      load: 1,
      reps: 10,
    },
    {
      id: "tjtBWbyHinyJzNQ3SphcW6",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-curl",
      order: 11,
      load: 1,
      reps: 10,
    },
    {
      id: "9qMN7iqQHMiaWNycKu5XpU",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-curl",
      order: 12,
      load: 1,
      reps: 10,
    },
    {
      id: "usxEdSNapBmAGKwRyXTWGJ",
      programId: "531-trident",
      routineId: "531-trident-16",
      exerciseId: "leg-curl",
      order: 13,
      load: 1,
      reps: 10,
    },
  ];
  await db.templates.bulkInsert(templates);
}
