import type { TemplatesDocType } from "./templates";

export const threeBy8TemplatesData: TemplatesDocType[] = [
  {
    id: "3x8-squat-a-1",
    programId: "3x8",
    routineId: "3x8-routine-1",
    exerciseId: "barbell-squat",
    order: 1,
    load: 0.85, // 85% of max for warmup
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-squat-a-2",
    programId: "3x8",
    routineId: "3x8-routine-1",
    exerciseId: "barbell-squat",
    order: 2,
    load: 0.9, // 90% of max for second set
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-squat-a-3",
    programId: "3x8",
    routineId: "3x8-routine-1",
    exerciseId: "barbell-squat",
    order: 3,
    load: 1.0, // 100% of max for working set
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 10,
      weightRoundingIncrement: 5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "3x8-bench-a-1",
    programId: "3x8",
    routineId: "3x8-routine-1",
    exerciseId: "barbell-bench-press",
    order: 4,
    load: 0.85,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-bench-a-2",
    programId: "3x8",
    routineId: "3x8-routine-1",
    exerciseId: "barbell-bench-press",
    order: 5,
    load: 0.9,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-bench-a-3",
    programId: "3x8",
    routineId: "3x8-routine-1",
    exerciseId: "barbell-bench-press",
    order: 6,
    load: 1.0,
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 5,
      weightRoundingIncrement: 5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "3x8-deadlift-a-1",
    programId: "3x8",
    routineId: "3x8-routine-1",
    exerciseId: "barbell-deadlift",
    order: 7,
    load: 1.0,
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 10,
      weightRoundingIncrement: 10,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "3x8-squat-b-1",
    programId: "3x8",
    routineId: "3x8-routine-2",
    exerciseId: "barbell-squat",
    order: 1,
    load: 0.85,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-squat-b-2",
    programId: "3x8",
    routineId: "3x8-routine-2",
    exerciseId: "barbell-squat",
    order: 2,
    load: 0.9,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-squat-b-3",
    programId: "3x8",
    routineId: "3x8-routine-2",
    exerciseId: "barbell-squat",
    order: 3,
    load: 1.0,
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 10,
      weightRoundingIncrement: 10,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "3x8-ohp-b-1",
    programId: "3x8",
    routineId: "3x8-routine-2",
    exerciseId: "barbell-overhead-press",
    order: 4,
    load: 0.85,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-ohp-b-2",
    programId: "3x8",
    routineId: "3x8-routine-2",
    exerciseId: "barbell-overhead-press",
    order: 5,
    load: 0.9,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-ohp-b-3",
    programId: "3x8",
    routineId: "3x8-routine-2",
    exerciseId: "barbell-overhead-press",
    order: 6,
    load: 1.0,
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 5,
      weightRoundingIncrement: 5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
  {
    id: "3x8-row-b-1",
    programId: "3x8",
    routineId: "3x8-routine-2",
    exerciseId: "barbell-row",
    order: 7,
    load: 0.85,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-row-b-2",
    programId: "3x8",
    routineId: "3x8-routine-2",
    exerciseId: "barbell-row",
    order: 8,
    load: 0.9,
    repRange: { min: 8, max: 8 },
  },
  {
    id: "3x8-row-b-3",
    programId: "3x8",
    routineId: "3x8-routine-2",
    exerciseId: "barbell-row",
    order: 9,
    load: 1.0,
    repRange: { min: 8, max: 8 },
    progressionConfig: {
      type: "linear" as const,
      incrementType: "fixed" as const,
      weightIncrement: 5,
      weightRoundingIncrement: 5,
      deloadStrategy: "percentage" as const,
      deloadType: "percentage" as const,
      deloadAmount: 0.1,
      failureThreshold: 3,
    },
  },
];
